package com.flare.im.contract

/** GENERATED. Do not edit by hand. */
object NativeCallMap {
    /** create maps to `flare_sdk_create` via `ffi-symbol`. Operation: `sdk.create`. */
    val SDK_CREATE = NativeCallDescriptor(module = "session", method = "create", operation = "sdk.create", transport = "ffi-symbol", cApi = "flare_sdk_create", requestEncoding = "none", responseEncoding = "handle", returnMode = "sync", handlePolicy = "create-handle")
    /** init maps to `flare_sdk_init` via `ffi-symbol`. Operation: `sdk.init`. */
    val SDK_INIT = NativeCallDescriptor(module = "session", method = "init", operation = "sdk.init", transport = "ffi-symbol", cApi = "flare_sdk_init", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** uninit maps to `flare_sdk_uninit` via `ffi-symbol`. Operation: `sdk.uninit`. */
    val SDK_UNINIT = NativeCallDescriptor(module = "session", method = "uninit", operation = "sdk.uninit", transport = "ffi-symbol", cApi = "flare_sdk_uninit", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** login maps to `flare_sdk_login` via `ffi-symbol`. Operation: `sdk.login`. */
    val SDK_LOGIN = NativeCallDescriptor(module = "session", method = "login", operation = "sdk.login", transport = "ffi-symbol", cApi = "flare_sdk_login", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** prepare maps to `flare_sdk_prepare` via `ffi-symbol`. Operation: `sdk.prepare`. */
    val SDK_PREPARE = NativeCallDescriptor(module = "session", method = "prepare", operation = "sdk.prepare", transport = "ffi-symbol", cApi = "flare_sdk_prepare", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** connect maps to `flare_sdk_connect` via `ffi-symbol`. Operation: `sdk.connect`. */
    val SDK_CONNECT = NativeCallDescriptor(module = "session", method = "connect", operation = "sdk.connect", transport = "ffi-symbol", cApi = "flare_sdk_connect", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** updateAccessToken maps to `flare_sdk_update_access_token` via `ffi-symbol`. Operation: `sdk.update_access_token`. */
    val SDK_UPDATE_ACCESS_TOKEN = NativeCallDescriptor(module = "session", method = "updateAccessToken", operation = "sdk.update_access_token", transport = "ffi-symbol", cApi = "flare_sdk_update_access_token", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** setHeartbeatAppState maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sdk.set_heartbeat_app_state`. */
    val SDK_SET_HEARTBEAT_APP_STATE = NativeCallDescriptor(module = "session", method = "setHeartbeatAppState", operation = "sdk.set_heartbeat_app_state", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** setHeartbeatNatTimeout maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sdk.set_heartbeat_nat_timeout`. */
    val SDK_SET_HEARTBEAT_NAT_TIMEOUT = NativeCallDescriptor(module = "session", method = "setHeartbeatNatTimeout", operation = "sdk.set_heartbeat_nat_timeout", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** heartbeatEffectiveInterval maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sdk.heartbeat_effective_interval`. */
    val SDK_HEARTBEAT_EFFECTIVE_INTERVAL = NativeCallDescriptor(module = "session", method = "heartbeatEffectiveInterval", operation = "sdk.heartbeat_effective_interval", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** logout maps to `flare_sdk_logout` via `ffi-symbol`. Operation: `sdk.logout`. */
    val SDK_LOGOUT = NativeCallDescriptor(module = "session", method = "logout", operation = "sdk.logout", transport = "ffi-symbol", cApi = "flare_sdk_logout", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** dispose maps to `flare_sdk_release` via `ffi-symbol`. Operation: `sdk.dispose`. */
    val SDK_DISPOSE = NativeCallDescriptor(module = "session", method = "dispose", operation = "sdk.dispose", transport = "ffi-symbol", cApi = "flare_sdk_release", requestEncoding = "handle", responseEncoding = "unit", returnMode = "sync", handlePolicy = "release-handle")
    /** hardReset maps to `flare_sdk_hard_reset` via `ffi-symbol`. Operation: `sdk.hard_reset`. */
    val SDK_HARD_RESET = NativeCallDescriptor(module = "session", method = "hardReset", operation = "sdk.hard_reset", transport = "ffi-symbol", cApi = "flare_sdk_hard_reset", requestEncoding = "none", responseEncoding = "unit", returnMode = "sync", handlePolicy = "reset-process")
    /** currentUserId maps to `flare_sdk_current_user_id` via `ffi-symbol`. Operation: `sdk.current_user_id`. */
    val SDK_CURRENT_USER_ID = NativeCallDescriptor(module = "session", method = "currentUserId", operation = "sdk.current_user_id", transport = "ffi-symbol", cApi = "flare_sdk_current_user_id", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** isConnected maps to `flare_sdk_is_connected` via `ffi-symbol`. Operation: `sdk.is_connected`. */
    val SDK_IS_CONNECTED = NativeCallDescriptor(module = "session", method = "isConnected", operation = "sdk.is_connected", transport = "ffi-symbol", cApi = "flare_sdk_is_connected", requestEncoding = "typed-ffi", responseEncoding = "boolean", returnMode = "sync", handlePolicy = "client-handle")
    /** sessionActive maps to `flare_sdk_session_active` via `ffi-symbol`. Operation: `sdk.session_active`. */
    val SDK_SESSION_ACTIVE = NativeCallDescriptor(module = "session", method = "sessionActive", operation = "sdk.session_active", transport = "ffi-symbol", cApi = "flare_sdk_session_active", requestEncoding = "typed-ffi", responseEncoding = "boolean", returnMode = "sync", handlePolicy = "client-handle")
    /** getConnectionState maps to `flare_sdk_state` via `ffi-symbol`. Operation: `connection.get_state`. */
    val CONNECTION_GET_STATE = NativeCallDescriptor(module = "connection", method = "getConnectionState", operation = "connection.get_state", transport = "ffi-symbol", cApi = "flare_sdk_state", requestEncoding = "typed-ffi", responseEncoding = "enum", returnMode = "sync", handlePolicy = "client-handle")
    /** disconnect maps to `flare_sdk_disconnect` via `ffi-symbol`. Operation: `connection.disconnect`. */
    val CONNECTION_DISCONNECT = NativeCallDescriptor(module = "connection", method = "disconnect", operation = "connection.disconnect", transport = "ffi-symbol", cApi = "flare_sdk_disconnect", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** notifyNetworkChange maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `connection.notify_network_change`. */
    val CONNECTION_NOTIFY_NETWORK_CHANGE = NativeCallDescriptor(module = "connection", method = "notifyNetworkChange", operation = "connection.notify_network_change", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listConversations maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list`. */
    val CONVERSATION_LIST = NativeCallDescriptor(module = "conversations", method = "listConversations", operation = "conversation.list", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listConversationsByQuery maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_by_query`. */
    val CONVERSATION_LIST_BY_QUERY = NativeCallDescriptor(module = "conversations", method = "listConversationsByQuery", operation = "conversation.list_by_query", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listConversationsIncludingArchived maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_including_archived`. */
    val CONVERSATION_LIST_INCLUDING_ARCHIVED = NativeCallDescriptor(module = "conversations", method = "listConversationsIncludingArchived", operation = "conversation.list_including_archived", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getConversation maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get`. */
    val CONVERSATION_GET = NativeCallDescriptor(module = "conversations", method = "getConversation", operation = "conversation.get", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getOneConversation maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get_one`. */
    val CONVERSATION_GET_ONE = NativeCallDescriptor(module = "conversations", method = "getOneConversation", operation = "conversation.get_one", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getGroupConversationByUserIds maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get_group_by_user_ids`. */
    val CONVERSATION_GET_GROUP_BY_USER_IDS = NativeCallDescriptor(module = "conversations", method = "getGroupConversationByUserIds", operation = "conversation.get_group_by_user_ids", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getMultipleConversations maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get_multiple`. */
    val CONVERSATION_GET_MULTIPLE = NativeCallDescriptor(module = "conversations", method = "getMultipleConversations", operation = "conversation.get_multiple", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listConversationsPaginated maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_paginated`. */
    val CONVERSATION_LIST_PAGINATED = NativeCallDescriptor(module = "conversations", method = "listConversationsPaginated", operation = "conversation.list_paginated", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listRawConversations maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_raw`. */
    val CONVERSATION_LIST_RAW = NativeCallDescriptor(module = "conversations", method = "listRawConversations", operation = "conversation.list_raw", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** bootstrapHomeTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.bootstrap_home`. */
    val CONVERSATION_BOOTSTRAP_HOME = NativeCallDescriptor(module = "conversations", method = "bootstrapHomeTimeline", operation = "conversation.bootstrap_home", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** openConversationTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.open_timeline`. */
    val CONVERSATION_OPEN_TIMELINE = NativeCallDescriptor(module = "conversations", method = "openConversationTimeline", operation = "conversation.open_timeline", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** markConversationRead maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.mark_read`. */
    val CONVERSATION_MARK_READ = NativeCallDescriptor(module = "conversations", method = "markConversationRead", operation = "conversation.mark_read", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** setConversationPinned maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.set_pinned`. */
    val CONVERSATION_SET_PINNED = NativeCallDescriptor(module = "conversations", method = "setConversationPinned", operation = "conversation.set_pinned", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** setConversationMuted maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.set_muted`. */
    val CONVERSATION_SET_MUTED = NativeCallDescriptor(module = "conversations", method = "setConversationMuted", operation = "conversation.set_muted", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** setConversationArchived maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.set_archived`. */
    val CONVERSATION_SET_ARCHIVED = NativeCallDescriptor(module = "conversations", method = "setConversationArchived", operation = "conversation.set_archived", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** markConversationUnread maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.mark_unread`. */
    val CONVERSATION_MARK_UNREAD = NativeCallDescriptor(module = "conversations", method = "markConversationUnread", operation = "conversation.mark_unread", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** deleteConversation maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.delete`. */
    val CONVERSATION_DELETE = NativeCallDescriptor(module = "conversations", method = "deleteConversation", operation = "conversation.delete", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** updateConversationDraft maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.update_draft`. */
    val CONVERSATION_UPDATE_DRAFT = NativeCallDescriptor(module = "conversations", method = "updateConversationDraft", operation = "conversation.update_draft", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** clearLocalChatHistory maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.clear_local_chat_history`. */
    val CONVERSATION_CLEAR_LOCAL_CHAT_HISTORY = NativeCallDescriptor(module = "conversations", method = "clearLocalChatHistory", operation = "conversation.clear_local_chat_history", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listSupportedBuildOperations maps to `flare_message_build_json` via `catalog-static`. Operation: `message_builder.list_catalog`. */
    val MESSAGE_BUILDER_LIST_CATALOG = NativeCallDescriptor(module = "message_builder", method = "listSupportedBuildOperations", operation = "message_builder.list_catalog", transport = "catalog-static", cApi = "flare_message_build_json", requestEncoding = "local-static", responseEncoding = "json-object", returnMode = "local", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** normalizeRichDocFromMarkdown maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `rich_doc_v2.normalize_from_markdown`. */
    val RICH_DOC_V2_NORMALIZE_FROM_MARKDOWN = NativeCallDescriptor(module = "message_builder", method = "normalizeRichDocFromMarkdown", operation = "rich_doc_v2.normalize_from_markdown", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** normalizeRichDocFromHtml maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `rich_doc_v2.normalize_from_html`. */
    val RICH_DOC_V2_NORMALIZE_FROM_HTML = NativeCallDescriptor(module = "message_builder", method = "normalizeRichDocFromHtml", operation = "rich_doc_v2.normalize_from_html", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** normalizeRichDocFromDocJson maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `rich_doc_v2.normalize_from_doc_json`. */
    val RICH_DOC_V2_NORMALIZE_FROM_DOC_JSON = NativeCallDescriptor(module = "message_builder", method = "normalizeRichDocFromDocJson", operation = "rich_doc_v2.normalize_from_doc_json", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** buildAnnouncement maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_announcement`. Operation: `message_builder.create_announcement`. */
    val MESSAGE_BUILDER_CREATE_ANNOUNCEMENT = NativeCallDescriptor(module = "message_builder", method = "buildAnnouncement", operation = "message_builder.create_announcement", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_announcement", callback = "FlareResultCallback")
    /** buildAudio maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_audio`. Operation: `message_builder.create_audio`. */
    val MESSAGE_BUILDER_CREATE_AUDIO = NativeCallDescriptor(module = "message_builder", method = "buildAudio", operation = "message_builder.create_audio", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_audio", callback = "FlareResultCallback")
    /** buildCard maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_card`. Operation: `message_builder.create_card`. */
    val MESSAGE_BUILDER_CREATE_CARD = NativeCallDescriptor(module = "message_builder", method = "buildCard", operation = "message_builder.create_card", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_card", callback = "FlareResultCallback")
    /** buildCustom maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_custom`. Operation: `message_builder.create_custom`. */
    val MESSAGE_BUILDER_CREATE_CUSTOM = NativeCallDescriptor(module = "message_builder", method = "buildCustom", operation = "message_builder.create_custom", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_custom", callback = "FlareResultCallback")
    /** buildEmoji maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_emoji`. Operation: `message_builder.create_emoji`. */
    val MESSAGE_BUILDER_CREATE_EMOJI = NativeCallDescriptor(module = "message_builder", method = "buildEmoji", operation = "message_builder.create_emoji", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_emoji", callback = "FlareResultCallback")
    /** buildFile maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_file`. Operation: `message_builder.create_file`. */
    val MESSAGE_BUILDER_CREATE_FILE = NativeCallDescriptor(module = "message_builder", method = "buildFile", operation = "message_builder.create_file", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_file", callback = "FlareResultCallback")
    /** buildForward maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_forward`. Operation: `message_builder.create_forward`. */
    val MESSAGE_BUILDER_CREATE_FORWARD = NativeCallDescriptor(module = "message_builder", method = "buildForward", operation = "message_builder.create_forward", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_forward", callback = "FlareResultCallback")
    /** buildImage maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_image`. Operation: `message_builder.create_image`. */
    val MESSAGE_BUILDER_CREATE_IMAGE = NativeCallDescriptor(module = "message_builder", method = "buildImage", operation = "message_builder.create_image", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_image", callback = "FlareResultCallback")
    /** buildImageGroup maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_image_group`. Operation: `message_builder.create_image_group`. */
    val MESSAGE_BUILDER_CREATE_IMAGE_GROUP = NativeCallDescriptor(module = "message_builder", method = "buildImageGroup", operation = "message_builder.create_image_group", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_image_group", callback = "FlareResultCallback")
    /** buildLinkCard maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_link_card`. Operation: `message_builder.create_link_card`. */
    val MESSAGE_BUILDER_CREATE_LINK_CARD = NativeCallDescriptor(module = "message_builder", method = "buildLinkCard", operation = "message_builder.create_link_card", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_link_card", callback = "FlareResultCallback")
    /** buildLocation maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_location`. Operation: `message_builder.create_location`. */
    val MESSAGE_BUILDER_CREATE_LOCATION = NativeCallDescriptor(module = "message_builder", method = "buildLocation", operation = "message_builder.create_location", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_location", callback = "FlareResultCallback")
    /** buildMiniProgram maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_mini_program`. Operation: `message_builder.create_mini_program`. */
    val MESSAGE_BUILDER_CREATE_MINI_PROGRAM = NativeCallDescriptor(module = "message_builder", method = "buildMiniProgram", operation = "message_builder.create_mini_program", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_mini_program", callback = "FlareResultCallback")
    /** buildNotification maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_notification`. Operation: `message_builder.create_notification`. */
    val MESSAGE_BUILDER_CREATE_NOTIFICATION = NativeCallDescriptor(module = "message_builder", method = "buildNotification", operation = "message_builder.create_notification", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_notification", callback = "FlareResultCallback")
    /** buildPlaceholder maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_placeholder`. Operation: `message_builder.create_placeholder`. */
    val MESSAGE_BUILDER_CREATE_PLACEHOLDER = NativeCallDescriptor(module = "message_builder", method = "buildPlaceholder", operation = "message_builder.create_placeholder", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_placeholder", callback = "FlareResultCallback")
    /** buildQuote maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_quote`. Operation: `message_builder.create_quote`. */
    val MESSAGE_BUILDER_CREATE_QUOTE = NativeCallDescriptor(module = "message_builder", method = "buildQuote", operation = "message_builder.create_quote", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_quote", callback = "FlareResultCallback")
    /** buildRichDoc maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_rich_doc`. Operation: `message_builder.create_rich_doc`. */
    val MESSAGE_BUILDER_CREATE_RICH_DOC = NativeCallDescriptor(module = "message_builder", method = "buildRichDoc", operation = "message_builder.create_rich_doc", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_rich_doc", callback = "FlareResultCallback")
    /** buildSchedule maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_schedule`. Operation: `message_builder.create_schedule`. */
    val MESSAGE_BUILDER_CREATE_SCHEDULE = NativeCallDescriptor(module = "message_builder", method = "buildSchedule", operation = "message_builder.create_schedule", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_schedule", callback = "FlareResultCallback")
    /** buildSticker maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_sticker`. Operation: `message_builder.create_sticker`. */
    val MESSAGE_BUILDER_CREATE_STICKER = NativeCallDescriptor(module = "message_builder", method = "buildSticker", operation = "message_builder.create_sticker", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_sticker", callback = "FlareResultCallback")
    /** buildSystem maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_system`. Operation: `message_builder.create_system`. */
    val MESSAGE_BUILDER_CREATE_SYSTEM = NativeCallDescriptor(module = "message_builder", method = "buildSystem", operation = "message_builder.create_system", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_system", callback = "FlareResultCallback")
    /** buildTask maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_task`. Operation: `message_builder.create_task`. */
    val MESSAGE_BUILDER_CREATE_TASK = NativeCallDescriptor(module = "message_builder", method = "buildTask", operation = "message_builder.create_task", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_task", callback = "FlareResultCallback")
    /** buildText maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_text`. Operation: `message_builder.create_text`. */
    val MESSAGE_BUILDER_CREATE_TEXT = NativeCallDescriptor(module = "message_builder", method = "buildText", operation = "message_builder.create_text", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_text", callback = "FlareResultCallback")
    /** buildThreadReply maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_thread_reply`. Operation: `message_builder.create_thread_reply`. */
    val MESSAGE_BUILDER_CREATE_THREAD_REPLY = NativeCallDescriptor(module = "message_builder", method = "buildThreadReply", operation = "message_builder.create_thread_reply", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_thread_reply", callback = "FlareResultCallback")
    /** buildVideo maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_video`. Operation: `message_builder.create_video`. */
    val MESSAGE_BUILDER_CREATE_VIDEO = NativeCallDescriptor(module = "message_builder", method = "buildVideo", operation = "message_builder.create_video", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_video", callback = "FlareResultCallback")
    /** buildVote maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_vote`. Operation: `message_builder.create_vote`. */
    val MESSAGE_BUILDER_CREATE_VOTE = NativeCallDescriptor(module = "message_builder", method = "buildVote", operation = "message_builder.create_vote", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_vote", callback = "FlareResultCallback")
    /** buildWithContent maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_with_content`. Operation: `message_builder.create_with_content`. */
    val MESSAGE_BUILDER_CREATE_WITH_CONTENT = NativeCallDescriptor(module = "message_builder", method = "buildWithContent", operation = "message_builder.create_with_content", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "create_with_content", callback = "FlareResultCallback")
    /** createTextMessage maps to `flare_message_create_text` via `ffi-symbol`. Operation: `message.create_text`. */
    val MESSAGE_CREATE_TEXT = NativeCallDescriptor(module = "messages", method = "createTextMessage", operation = "message.create_text", transport = "ffi-symbol", cApi = "flare_message_create_text", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** dispatchMessage maps to `flare_message_dispatch_json` via `dispatch-json`. Operation: `message.dispatch`. */
    val MESSAGE_DISPATCH = NativeCallDescriptor(module = "messages", method = "dispatchMessage", operation = "message.dispatch", transport = "dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** sendMessageNoOss maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `send_no_oss`. Operation: `message.send_no_oss`. */
    val MESSAGE_SEND_NO_OSS = NativeCallDescriptor(module = "messages", method = "sendMessageNoOss", operation = "message.send_no_oss", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "send_no_oss", callback = "FlareResultCallback")
    /** sendMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `send`. Operation: `message.send`. */
    val MESSAGE_SEND = NativeCallDescriptor(module = "messages", method = "sendMessage", operation = "message.send", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "send", callback = "FlareResultCallback")
    /** listMessages maps to `flare_message_list` via `ffi-symbol`. Operation: `message.list`. */
    val MESSAGE_LIST = NativeCallDescriptor(module = "messages", method = "listMessages", operation = "message.list", transport = "ffi-symbol", cApi = "flare_message_list", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** recallMessage maps to `flare_message_recall` via `ffi-symbol`. Operation: `message.recall`. */
    val MESSAGE_RECALL = NativeCallDescriptor(module = "messages", method = "recallMessage", operation = "message.recall", transport = "ffi-symbol", cApi = "flare_message_recall", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** editTextByMessageId maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `edit_text_by_message_id`. Operation: `message.edit_text_by_message_id`. */
    val MESSAGE_EDIT_TEXT_BY_MESSAGE_ID = NativeCallDescriptor(module = "messages", method = "editTextByMessageId", operation = "message.edit_text_by_message_id", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "edit_text_by_message_id", callback = "FlareResultCallback")
    /** deleteMessage maps to `flare_message_delete` via `ffi-symbol`. Operation: `message.delete`. */
    val MESSAGE_DELETE = NativeCallDescriptor(module = "messages", method = "deleteMessage", operation = "message.delete", transport = "ffi-symbol", cApi = "flare_message_delete", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** deleteMessageForSelf maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `delete_for_self`. Operation: `message.delete_for_self`. */
    val MESSAGE_DELETE_FOR_SELF = NativeCallDescriptor(module = "messages", method = "deleteMessageForSelf", operation = "message.delete_for_self", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "delete_for_self", callback = "FlareResultCallback")
    /** deleteMessageForEveryone maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `delete_for_everyone`. Operation: `message.delete_for_everyone`. */
    val MESSAGE_DELETE_FOR_EVERYONE = NativeCallDescriptor(module = "messages", method = "deleteMessageForEveryone", operation = "message.delete_for_everyone", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "delete_for_everyone", callback = "FlareResultCallback")
    /** markMessageReadAndBurn maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark_read_and_burn`. Operation: `message.mark_read_and_burn`. */
    val MESSAGE_MARK_READ_AND_BURN = NativeCallDescriptor(module = "messages", method = "markMessageReadAndBurn", operation = "message.mark_read_and_burn", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "mark_read_and_burn", callback = "FlareResultCallback")
    /** addReaction maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `add_reaction`. Operation: `message.add_reaction`. */
    val MESSAGE_ADD_REACTION = NativeCallDescriptor(module = "messages", method = "addReaction", operation = "message.add_reaction", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "add_reaction", callback = "FlareResultCallback")
    /** removeReaction maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `remove_reaction`. Operation: `message.remove_reaction`. */
    val MESSAGE_REMOVE_REACTION = NativeCallDescriptor(module = "messages", method = "removeReaction", operation = "message.remove_reaction", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "remove_reaction", callback = "FlareResultCallback")
    /** pinMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `pin`. Operation: `message.pin`. */
    val MESSAGE_PIN = NativeCallDescriptor(module = "messages", method = "pinMessage", operation = "message.pin", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "pin", callback = "FlareResultCallback")
    /** unpinMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unpin`. Operation: `message.unpin`. */
    val MESSAGE_UNPIN = NativeCallDescriptor(module = "messages", method = "unpinMessage", operation = "message.unpin", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "unpin", callback = "FlareResultCallback")
    /** pinMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `pin_by_message_id`. Operation: `message.pin_by_message_id`. */
    val MESSAGE_PIN_BY_MESSAGE_ID = NativeCallDescriptor(module = "messages", method = "pinMessageById", operation = "message.pin_by_message_id", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "pin_by_message_id", callback = "FlareResultCallback")
    /** unpinMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unpin_by_message_id`. Operation: `message.unpin_by_message_id`. */
    val MESSAGE_UNPIN_BY_MESSAGE_ID = NativeCallDescriptor(module = "messages", method = "unpinMessageById", operation = "message.unpin_by_message_id", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "unpin_by_message_id", callback = "FlareResultCallback")
    /** markMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark`. Operation: `message.mark`. */
    val MESSAGE_MARK = NativeCallDescriptor(module = "messages", method = "markMessage", operation = "message.mark", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "mark", callback = "FlareResultCallback")
    /** markMessageWithColor maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark_with_color`. Operation: `message.mark_with_color`. */
    val MESSAGE_MARK_WITH_COLOR = NativeCallDescriptor(module = "messages", method = "markMessageWithColor", operation = "message.mark_with_color", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "mark_with_color", callback = "FlareResultCallback")
    /** unmarkMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unmark`. Operation: `message.unmark`. */
    val MESSAGE_UNMARK = NativeCallDescriptor(module = "messages", method = "unmarkMessage", operation = "message.unmark", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "unmark", callback = "FlareResultCallback")
    /** markMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark_by_message_id`. Operation: `message.mark_by_message_id`. */
    val MESSAGE_MARK_BY_MESSAGE_ID = NativeCallDescriptor(module = "messages", method = "markMessageById", operation = "message.mark_by_message_id", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "mark_by_message_id", callback = "FlareResultCallback")
    /** unmarkMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unmark_by_message_id`. Operation: `message.unmark_by_message_id`. */
    val MESSAGE_UNMARK_BY_MESSAGE_ID = NativeCallDescriptor(module = "messages", method = "unmarkMessageById", operation = "message.unmark_by_message_id", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "unmark_by_message_id", callback = "FlareResultCallback")
    /** getMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `get`. Operation: `message.get`. */
    val MESSAGE_GET = NativeCallDescriptor(module = "messages", method = "getMessage", operation = "message.get", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "get", callback = "FlareResultCallback")
    /** getRawMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `get_raw`. Operation: `message.get_raw`. */
    val MESSAGE_GET_RAW = NativeCallDescriptor(module = "messages", method = "getRawMessage", operation = "message.get_raw", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "get_raw", callback = "FlareResultCallback")
    /** searchMessages maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `search`. Operation: `message.search`. */
    val MESSAGE_SEARCH = NativeCallDescriptor(module = "messages", method = "searchMessages", operation = "message.search", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "search", callback = "FlareResultCallback")
    /** searchMessagesByQuery maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `search_by_query`. Operation: `message.search_by_query`. */
    val MESSAGE_SEARCH_BY_QUERY = NativeCallDescriptor(module = "messages", method = "searchMessagesByQuery", operation = "message.search_by_query", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "search_by_query", callback = "FlareResultCallback")
    /** searchMessagesInConversation maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `search_in_conversation`. Operation: `message.search_in_conversation`. */
    val MESSAGE_SEARCH_IN_CONVERSATION = NativeCallDescriptor(module = "messages", method = "searchMessagesInConversation", operation = "message.search_in_conversation", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "search_in_conversation", callback = "FlareResultCallback")
    /** editRichDocByMessageId maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `edit_rich_doc_by_message_id`. Operation: `message.edit_rich_doc_by_message_id`. */
    val MESSAGE_EDIT_RICH_DOC_BY_MESSAGE_ID = NativeCallDescriptor(module = "messages", method = "editRichDocByMessageId", operation = "message.edit_rich_doc_by_message_id", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "edit_rich_doc_by_message_id", callback = "FlareResultCallback")
    /** setTyping maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `typing`. Operation: `message.typing`. */
    val MESSAGE_TYPING = NativeCallDescriptor(module = "messages", method = "setTyping", operation = "message.typing", transport = "message-dispatch-json", cApi = "flare_message_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "typing", callback = "FlareResultCallback")
    /** syncConversationSummaries maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.conversation_summaries`. */
    val SYNC_CONVERSATION_SUMMARIES = NativeCallDescriptor(module = "sync", method = "syncConversationSummaries", operation = "sync.conversation_summaries", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** syncConversationSummariesWithVersions maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.conversation_summaries_with_versions`. */
    val SYNC_CONVERSATION_SUMMARIES_WITH_VERSIONS = NativeCallDescriptor(module = "sync", method = "syncConversationSummariesWithVersions", operation = "sync.conversation_summaries_with_versions", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** bootstrapStartupHome maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.bootstrap_startup_home`. */
    val SYNC_BOOTSTRAP_STARTUP_HOME = NativeCallDescriptor(module = "sync", method = "bootstrapStartupHome", operation = "sync.bootstrap_startup_home", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** backfillConversationHistory maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.conversation_history_backfill`. */
    val SYNC_CONVERSATION_HISTORY_BACKFILL = NativeCallDescriptor(module = "sync", method = "backfillConversationHistory", operation = "sync.conversation_history_backfill", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** syncConversation maps to `flare_sdk_sync_conversation` via `ffi-symbol`. Operation: `sync.conversation`. */
    val SYNC_CONVERSATION = NativeCallDescriptor(module = "sync", method = "syncConversation", operation = "sync.conversation", transport = "ffi-symbol", cApi = "flare_sdk_sync_conversation", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** syncMessages maps to `flare_sdk_sync_messages` via `ffi-symbol`. Operation: `sync.messages`. */
    val SYNC_MESSAGES = NativeCallDescriptor(module = "sync", method = "syncMessages", operation = "sync.messages", transport = "ffi-symbol", cApi = "flare_sdk_sync_messages", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** upsertUserProfiles maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `user.upsert_profiles`. */
    val USER_UPSERT_PROFILES = NativeCallDescriptor(module = "user", method = "upsertUserProfiles", operation = "user.upsert_profiles", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getUserPresence maps to `flare_sdk_get_user_presence` via `ffi-symbol`. Operation: `presence.get`. */
    val PRESENCE_GET = NativeCallDescriptor(module = "presence", method = "getUserPresence", operation = "presence.get", transport = "ffi-symbol", cApi = "flare_sdk_get_user_presence", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** batchGetUserPresence maps to `flare_sdk_batch_get_user_presence` via `ffi-symbol`. Operation: `presence.batch_get`. */
    val PRESENCE_BATCH_GET = NativeCallDescriptor(module = "presence", method = "batchGetUserPresence", operation = "presence.batch_get", transport = "ffi-symbol", cApi = "flare_sdk_batch_get_user_presence", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** subscribeUserPresence maps to `flare_sdk_subscribe_user_presence` via `ffi-symbol`. Operation: `presence.subscribe`. */
    val PRESENCE_SUBSCRIBE = NativeCallDescriptor(module = "presence", method = "subscribeUserPresence", operation = "presence.subscribe", transport = "ffi-symbol", cApi = "flare_sdk_subscribe_user_presence", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** uploadFile maps to `flare_media_upload_file` via `ffi-symbol`. Operation: `media.upload_file`. */
    val MEDIA_UPLOAD_FILE = NativeCallDescriptor(module = "media", method = "uploadFile", operation = "media.upload_file", transport = "ffi-symbol", cApi = "flare_media_upload_file", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** uploadImage maps to `flare_media_upload_image` via `ffi-symbol`. Operation: `media.upload_image`. */
    val MEDIA_UPLOAD_IMAGE = NativeCallDescriptor(module = "media", method = "uploadImage", operation = "media.upload_image", transport = "ffi-symbol", cApi = "flare_media_upload_image", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** uploadVideo maps to `flare_media_upload_video` via `ffi-symbol`. Operation: `media.upload_video`. */
    val MEDIA_UPLOAD_VIDEO = NativeCallDescriptor(module = "media", method = "uploadVideo", operation = "media.upload_video", transport = "ffi-symbol", cApi = "flare_media_upload_video", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** uploadBytes maps to `flare_media_upload_bytes` via `ffi-symbol`. Operation: `media.upload_bytes`. */
    val MEDIA_UPLOAD_BYTES = NativeCallDescriptor(module = "media", method = "uploadBytes", operation = "media.upload_bytes", transport = "ffi-symbol", cApi = "flare_media_upload_bytes", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** deleteFile maps to `flare_media_delete_file` via `ffi-symbol`. Operation: `media.delete_file`. */
    val MEDIA_DELETE_FILE = NativeCallDescriptor(module = "media", method = "deleteFile", operation = "media.delete_file", transport = "ffi-symbol", cApi = "flare_media_delete_file", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getMediaUrl maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `get_url`. Operation: `media.get_url`. */
    val MEDIA_GET_URL = NativeCallDescriptor(module = "media", method = "getMediaUrl", operation = "media.get_url", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "get_url", callback = "FlareResultCallback")
    /** getTempDownloadUrl maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `temp_download_url`. Operation: `media.temp_download_url`. */
    val MEDIA_TEMP_DOWNLOAD_URL = NativeCallDescriptor(module = "media", method = "getTempDownloadUrl", operation = "media.temp_download_url", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "temp_download_url", callback = "FlareResultCallback")
    /** resolveMediaAccess maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `resolve_access`. Operation: `media.resolve_access`. */
    val MEDIA_RESOLVE_ACCESS = NativeCallDescriptor(module = "media", method = "resolveMediaAccess", operation = "media.resolve_access", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "resolve_access", callback = "FlareResultCallback")
    /** cacheRemoteMedia maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `cache_remote`. Operation: `media.cache_remote`. */
    val MEDIA_CACHE_REMOTE = NativeCallDescriptor(module = "media", method = "cacheRemoteMedia", operation = "media.cache_remote", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "cache_remote", callback = "FlareResultCallback")
    /** getMediaCacheStats maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `cache_stats`. Operation: `media.cache_stats`. */
    val MEDIA_CACHE_STATS = NativeCallDescriptor(module = "media", method = "getMediaCacheStats", operation = "media.cache_stats", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "cache_stats", callback = "FlareResultCallback")
    /** setMediaCacheMaxBytes maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `set_cache_max_bytes`. Operation: `media.set_cache_max_bytes`. */
    val MEDIA_SET_CACHE_MAX_BYTES = NativeCallDescriptor(module = "media", method = "setMediaCacheMaxBytes", operation = "media.set_cache_max_bytes", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "set_cache_max_bytes", callback = "FlareResultCallback")
    /** setMediaCacheRoot maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `set_cache_root`. Operation: `media.set_cache_root`. */
    val MEDIA_SET_CACHE_ROOT = NativeCallDescriptor(module = "media", method = "setMediaCacheRoot", operation = "media.set_cache_root", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "set_cache_root", callback = "FlareResultCallback")
    /** clearMediaCache maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `clear_cache`. Operation: `media.clear_cache`. */
    val MEDIA_CLEAR_CACHE = NativeCallDescriptor(module = "media", method = "clearMediaCache", operation = "media.clear_cache", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "clear_cache", callback = "FlareResultCallback")
    /** getUserDownloadSubfolder maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_get_subfolder`. Operation: `media.user_download_get_subfolder`. */
    val MEDIA_USER_DOWNLOAD_GET_SUBFOLDER = NativeCallDescriptor(module = "media", method = "getUserDownloadSubfolder", operation = "media.user_download_get_subfolder", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "user_download_get_subfolder", callback = "FlareResultCallback")
    /** setUserDownloadSubfolder maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_set_subfolder`. Operation: `media.user_download_set_subfolder`. */
    val MEDIA_USER_DOWNLOAD_SET_SUBFOLDER = NativeCallDescriptor(module = "media", method = "setUserDownloadSubfolder", operation = "media.user_download_set_subfolder", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "user_download_set_subfolder", callback = "FlareResultCallback")
    /** getUserDownloadSavedPath maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_get_saved_path`. Operation: `media.user_download_get_saved_path`. */
    val MEDIA_USER_DOWNLOAD_GET_SAVED_PATH = NativeCallDescriptor(module = "media", method = "getUserDownloadSavedPath", operation = "media.user_download_get_saved_path", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "user_download_get_saved_path", callback = "FlareResultCallback")
    /** deleteUserDownloadRecord maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_delete_record`. Operation: `media.user_download_delete_record`. */
    val MEDIA_USER_DOWNLOAD_DELETE_RECORD = NativeCallDescriptor(module = "media", method = "deleteUserDownloadRecord", operation = "media.user_download_delete_record", transport = "media-dispatch-json", cApi = "flare_media_dispatch_json", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "user_download_delete_record", callback = "FlareResultCallback")
    /** cancelUserFileDownload maps to `flare_media_cancel_user_file_download` via `ffi-symbol`. Operation: `media.cancel_user_file_download`. */
    val MEDIA_CANCEL_USER_FILE_DOWNLOAD = NativeCallDescriptor(module = "media", method = "cancelUserFileDownload", operation = "media.cancel_user_file_download", transport = "ffi-symbol", cApi = "flare_media_cancel_user_file_download", requestEncoding = "typed-ffi", responseEncoding = "boolean", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** downloadFileToDownloads maps to `flare_media_download_file_to_downloads` via `ffi-symbol`. Operation: `media.download_file_to_downloads`. */
    val MEDIA_DOWNLOAD_FILE_TO_DOWNLOADS = NativeCallDescriptor(module = "media", method = "downloadFileToDownloads", operation = "media.download_file_to_downloads", transport = "ffi-symbol", cApi = "flare_media_download_file_to_downloads", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** listCapabilities maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_list`. Operation: `capability.list`. */
    val CAPABILITY_LIST = NativeCallDescriptor(module = "capabilities", method = "listCapabilities", operation = "capability.list", transport = "capability-dispatch-json", cApi = "flare_capability_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "capability_list", callback = "FlareResultCallback")
    /** listUserCapabilities maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_list_user`. Operation: `capability.list_user`. */
    val CAPABILITY_LIST_USER = NativeCallDescriptor(module = "capabilities", method = "listUserCapabilities", operation = "capability.list_user", transport = "capability-dispatch-json", cApi = "flare_capability_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "capability_list_user", callback = "FlareResultCallback")
    /** dispatchCapability maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_dispatch`. Operation: `capability.dispatch`. */
    val CAPABILITY_DISPATCH = NativeCallDescriptor(module = "capabilities", method = "dispatchCapability", operation = "capability.dispatch", transport = "capability-dispatch-json", cApi = "flare_capability_dispatch_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", dispatchOp = "capability_dispatch", callback = "FlareResultCallback")
    /** grantCapability maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_grant`. Operation: `capability.grant`. */
    val CAPABILITY_GRANT = NativeCallDescriptor(module = "capabilities", method = "grantCapability", operation = "capability.grant", transport = "capability-dispatch-json", cApi = "flare_capability_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "capability_grant", callback = "FlareResultCallback")
    /** revokeCapability maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_revoke`. Operation: `capability.revoke`. */
    val CAPABILITY_REVOKE = NativeCallDescriptor(module = "capabilities", method = "revokeCapability", operation = "capability.revoke", transport = "capability-dispatch-json", cApi = "flare_capability_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "capability_revoke", callback = "FlareResultCallback")
    /** sendCallSignal maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `send_call_signal`. Operation: `capability.send_call_signal`. */
    val CAPABILITY_SEND_CALL_SIGNAL = NativeCallDescriptor(module = "capabilities", method = "sendCallSignal", operation = "capability.send_call_signal", transport = "capability-dispatch-json", cApi = "flare_capability_dispatch_json", requestEncoding = "json", responseEncoding = "unit", returnMode = "callback-unit", handlePolicy = "client-handle", dispatchOp = "send_call_signal", callback = "FlareResultCallback")
    /** openTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.timeline.open`. */
    val VIEW_TIMELINE_OPEN = NativeCallDescriptor(module = "views", method = "openTimeline", operation = "view.timeline.open", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** loadOlderTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.timeline.load_older`. */
    val VIEW_TIMELINE_LOAD_OLDER = NativeCallDescriptor(module = "views", method = "loadOlderTimeline", operation = "view.timeline.load_older", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** openConversationList maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.conversation_list.open`. */
    val VIEW_CONVERSATION_LIST_OPEN = NativeCallDescriptor(module = "views", method = "openConversationList", operation = "view.conversation_list.open", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** close maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.close`. */
    val VIEW_CLOSE = NativeCallDescriptor(module = "views", method = "close", operation = "view.close", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** subscribeEvents maps to `flare_event_subscribe` via `ffi-symbol`. Operation: `event.subscribe`. */
    val EVENT_SUBSCRIBE = NativeCallDescriptor(module = "events", method = "subscribeEvents", operation = "event.subscribe", transport = "ffi-symbol", cApi = "flare_event_subscribe", requestEncoding = "typed-ffi", responseEncoding = "subscription", returnMode = "event-stream", handlePolicy = "client-handle", callback = "FlareEventCallback")
    /** subscribeEventsBatch maps to `flare_event_subscribe_batch` via `ffi-symbol`. Operation: `event.subscribe_batch`. */
    val EVENT_SUBSCRIBE_BATCH = NativeCallDescriptor(module = "events", method = "subscribeEventsBatch", operation = "event.subscribe_batch", transport = "ffi-symbol", cApi = "flare_event_subscribe_batch", requestEncoding = "typed-ffi", responseEncoding = "subscription", returnMode = "event-stream", handlePolicy = "client-handle", callback = "FlareEventBatchCallback")
    /** unsubscribe maps to `flare_event_unsubscribe` via `ffi-symbol`. Operation: `event.unsubscribe`. */
    val EVENT_UNSUBSCRIBE = NativeCallDescriptor(module = "events", method = "unsubscribe", operation = "event.unsubscribe", transport = "ffi-symbol", cApi = "flare_event_unsubscribe", requestEncoding = "typed-ffi", responseEncoding = "unit", returnMode = "sync", handlePolicy = "subscription-handle")
    /** unsubscribeAll maps to `flare_event_unsubscribe_all` via `ffi-symbol`. Operation: `event.unsubscribe_all`. */
    val EVENT_UNSUBSCRIBE_ALL = NativeCallDescriptor(module = "events", method = "unsubscribeAll", operation = "event.unsubscribe_all", transport = "ffi-symbol", cApi = "flare_event_unsubscribe_all", requestEncoding = "none", responseEncoding = "unit", returnMode = "sync", handlePolicy = "process")
    /** getSdkVersion maps to `flare_sdk_version` via `ffi-symbol`. Operation: `diagnostics.sdk_version`. */
    val DIAGNOSTICS_SDK_VERSION = NativeCallDescriptor(module = "diagnostics", method = "getSdkVersion", operation = "diagnostics.sdk_version", transport = "ffi-symbol", cApi = "flare_sdk_version", requestEncoding = "none", responseEncoding = "json-object", returnMode = "sync-string", handlePolicy = "process")
    /** getFfiContractVersion maps to `flare_sdk_ffi_contract_version` via `ffi-symbol`. Operation: `diagnostics.ffi_contract_version`. */
    val DIAGNOSTICS_FFI_CONTRACT_VERSION = NativeCallDescriptor(module = "diagnostics", method = "getFfiContractVersion", operation = "diagnostics.ffi_contract_version", transport = "ffi-symbol", cApi = "flare_sdk_ffi_contract_version", requestEncoding = "none", responseEncoding = "json-object", returnMode = "sync-string", handlePolicy = "process")
    /** getDataRoot maps to `flare_sdk_data_root` via `ffi-symbol`. Operation: `diagnostics.data_root`. */
    val DIAGNOSTICS_DATA_ROOT = NativeCallDescriptor(module = "diagnostics", method = "getDataRoot", operation = "diagnostics.data_root", transport = "ffi-symbol", cApi = "flare_sdk_data_root", requestEncoding = "typed-ffi", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** getRuntimeHealth maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `diagnostics.runtime_health`. */
    val DIAGNOSTICS_RUNTIME_HEALTH = NativeCallDescriptor(module = "diagnostics", method = "getRuntimeHealth", operation = "diagnostics.runtime_health", transport = "contract-invoke-json", cApi = "flare_sdk_invoke_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
    /** Internal typed message builder dispatch over `flare_message_build_json`. */
    val MESSAGE_BUILDER_DISPATCH = NativeCallDescriptor(module = "message_builder", method = "dispatchTypedBuild", operation = "message_builder.dispatch", transport = "dispatch-json", cApi = "flare_message_build_json", requestEncoding = "json", responseEncoding = "json-object", returnMode = "callback", handlePolicy = "client-handle", callback = "FlareResultCallback")
}
