/**
 * GENERATED. Do not edit by hand.
 *
 * Contract constants (operations, events, connection states, errors).
 */
export const ffiContractVersion = 'flare-im-ffi/v1' as const;
/** Canonical SDK module keys. */
export type SdkModule = 'session' | 'connection' | 'conversations' | 'message_builder' | 'messages' | 'sync' | 'presence' | 'media' | 'capabilities' | 'events' | 'diagnostics';
/** Canonical operation identifiers shared by every platform SDK. */
export type SdkOperation = 'sdk.create' | 'sdk.init' | 'sdk.uninit' | 'sdk.login' | 'sdk.prepare' | 'sdk.connect' | 'sdk.update_access_token' | 'sdk.set_heartbeat_app_state' | 'sdk.set_heartbeat_nat_timeout' | 'sdk.heartbeat_effective_interval' | 'sdk.logout' | 'sdk.dispose' | 'sdk.hard_reset' | 'sdk.current_user_id' | 'sdk.is_connected' | 'sdk.session_active' | 'connection.get_state' | 'connection.disconnect' | 'connection.notify_network_change' | 'conversation.list' | 'conversation.list_by_query' | 'conversation.list_including_archived' | 'conversation.get' | 'conversation.get_one' | 'conversation.get_group_by_user_ids' | 'conversation.get_multiple' | 'conversation.list_paginated' | 'conversation.list_raw' | 'conversation.bootstrap_home' | 'conversation.open_timeline' | 'conversation.mark_read' | 'conversation.set_pinned' | 'conversation.set_muted' | 'conversation.set_archived' | 'conversation.mark_unread' | 'conversation.delete' | 'conversation.update_draft' | 'conversation.clear_local_chat_history' | 'message_builder.list_catalog' | 'rich_doc_v2.normalize_from_markdown' | 'rich_doc_v2.normalize_from_html' | 'rich_doc_v2.normalize_from_doc_json' | 'message_builder.create_announcement' | 'message_builder.create_audio' | 'message_builder.create_card' | 'message_builder.create_custom' | 'message_builder.create_emoji' | 'message_builder.create_file' | 'message_builder.create_forward' | 'message_builder.create_image' | 'message_builder.create_image_group' | 'message_builder.create_link_card' | 'message_builder.create_location' | 'message_builder.create_mini_program' | 'message_builder.create_notification' | 'message_builder.create_placeholder' | 'message_builder.create_quote' | 'message_builder.create_rich_doc' | 'message_builder.create_schedule' | 'message_builder.create_sticker' | 'message_builder.create_system' | 'message_builder.create_task' | 'message_builder.create_text' | 'message_builder.create_thread_reply' | 'message_builder.create_video' | 'message_builder.create_vote' | 'message_builder.create_with_content' | 'message.create_text' | 'message.dispatch' | 'message.send_no_oss' | 'message.send' | 'message.list' | 'message.recall' | 'message.edit_text_by_message_id' | 'message.delete' | 'message.delete_for_self' | 'message.delete_for_everyone' | 'message.mark_read_and_burn' | 'message.add_reaction' | 'message.remove_reaction' | 'message.pin' | 'message.unpin' | 'message.pin_by_message_id' | 'message.unpin_by_message_id' | 'message.mark' | 'message.mark_with_color' | 'message.unmark' | 'message.mark_by_message_id' | 'message.unmark_by_message_id' | 'message.get' | 'message.get_raw' | 'message.search' | 'message.search_by_query' | 'message.search_in_conversation' | 'message.edit_rich_doc_by_message_id' | 'message.typing' | 'sync.conversation_summaries' | 'sync.conversation_summaries_with_versions' | 'sync.conversation' | 'sync.messages' | 'sync.conversation_history_backfill' | 'presence.get' | 'presence.batch_get' | 'presence.subscribe' | 'media.upload_file' | 'media.upload_image' | 'media.upload_video' | 'media.upload_bytes' | 'media.delete_file' | 'media.get_url' | 'media.temp_download_url' | 'media.resolve_access' | 'media.cache_remote' | 'media.cache_stats' | 'media.set_cache_max_bytes' | 'media.set_cache_root' | 'media.clear_cache' | 'media.user_download_get_subfolder' | 'media.user_download_set_subfolder' | 'media.user_download_get_saved_path' | 'media.user_download_delete_record' | 'media.cancel_user_file_download' | 'media.download_file_to_downloads' | 'capability.list' | 'capability.list_user' | 'capability.dispatch' | 'capability.grant' | 'capability.revoke' | 'capability.send_call_signal' | 'event.subscribe' | 'event.subscribe_batch' | 'event.unsubscribe' | 'event.unsubscribe_all' | 'diagnostics.sdk_version' | 'diagnostics.ffi_contract_version' | 'diagnostics.data_root' | 'diagnostics.runtime_health';
/** Stable machine-readable SDK error codes. */
export type SdkErrorCode = 'invalidParameter' | 'notInitialized' | 'notConnected' | 'unauthorized' | 'permissionDenied' | 'timeout' | 'networkUnavailable' | 'storageUnavailable' | 'operationCancelled' | 'capabilityUnavailable' | 'internal';
/** Public connection states exposed by client.connection. */
export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'ready' | 'reconnecting';
/** Event names emitted by the typed event stream. */
export type SdkEventName = 'burn_scheduled' | 'burned' | 'cache_changed' | 'call_signal' | 'capability' | 'changed' | 'connected' | 'connecting' | 'created' | 'custom' | 'deleted' | 'disconnected' | 'disposed' | 'download_progress' | 'edited' | 'event' | 'failed' | 'finished' | 'hard_deleted' | 'init_failed' | 'initialized' | 'initializing' | 'kicked_off' | 'logged_out' | 'login_failed' | 'login_succeeded' | 'marked' | 'pinned' | 'presence_changed' | 'progress' | 'reaction_changed' | 'read_receipt' | 'ready' | 'recalled' | 'received' | 'received_batch' | 'reconnect_failed' | 'reconnecting' | 'resync_needed' | 'retention_expired' | 'retention_purged' | 'retention_scheduled' | 'send_ack' | 'send_failed' | 'server_error' | 'started' | 'state_changed' | 'sync_state_changed' | 'synced' | 'task_completed' | 'token_expired' | 'typing' | 'unavailable' | 'unmarked' | 'unpinned' | 'unread_count_changed' | 'updated' | 'upload_progress';

/** Shared error envelope preserved across platform adapters. */
export interface FlareSdkError {
  code: SdkErrorCode;
  message: string;
  operation?: string;
  retryable?: boolean;
  details?: Record<string, unknown>;
  cause?: unknown;
}

/** Operation constants for bridge and adapter implementations. */
export const SdkOperations = {
  sdkCreate: 'sdk.create',
  sdkInit: 'sdk.init',
  sdkUninit: 'sdk.uninit',
  sdkLogin: 'sdk.login',
  sdkPrepare: 'sdk.prepare',
  sdkConnect: 'sdk.connect',
  sdkUpdateAccessToken: 'sdk.update_access_token',
  sdkSetHeartbeatAppState: 'sdk.set_heartbeat_app_state',
  sdkSetHeartbeatNatTimeout: 'sdk.set_heartbeat_nat_timeout',
  sdkHeartbeatEffectiveInterval: 'sdk.heartbeat_effective_interval',
  sdkLogout: 'sdk.logout',
  sdkDispose: 'sdk.dispose',
  sdkHardReset: 'sdk.hard_reset',
  sdkCurrentUserId: 'sdk.current_user_id',
  sdkIsConnected: 'sdk.is_connected',
  sdkSessionActive: 'sdk.session_active',
  connectionGetState: 'connection.get_state',
  connectionDisconnect: 'connection.disconnect',
  connectionNotifyNetworkChange: 'connection.notify_network_change',
  conversationList: 'conversation.list',
  conversationListByQuery: 'conversation.list_by_query',
  conversationListIncludingArchived: 'conversation.list_including_archived',
  conversationGet: 'conversation.get',
  conversationGetOne: 'conversation.get_one',
  conversationGetGroupByUserIds: 'conversation.get_group_by_user_ids',
  conversationGetMultiple: 'conversation.get_multiple',
  conversationListPaginated: 'conversation.list_paginated',
  conversationListRaw: 'conversation.list_raw',
  conversationBootstrapHome: 'conversation.bootstrap_home',
  conversationOpenTimeline: 'conversation.open_timeline',
  conversationMarkRead: 'conversation.mark_read',
  conversationSetPinned: 'conversation.set_pinned',
  conversationSetMuted: 'conversation.set_muted',
  conversationSetArchived: 'conversation.set_archived',
  conversationMarkUnread: 'conversation.mark_unread',
  conversationDelete: 'conversation.delete',
  conversationUpdateDraft: 'conversation.update_draft',
  conversationClearLocalChatHistory: 'conversation.clear_local_chat_history',
  messageBuilderListCatalog: 'message_builder.list_catalog',
  richDocV2NormalizeFromMarkdown: 'rich_doc_v2.normalize_from_markdown',
  richDocV2NormalizeFromHtml: 'rich_doc_v2.normalize_from_html',
  richDocV2NormalizeFromDocJson: 'rich_doc_v2.normalize_from_doc_json',
  messageBuilderCreateAnnouncement: 'message_builder.create_announcement',
  messageBuilderCreateAudio: 'message_builder.create_audio',
  messageBuilderCreateCard: 'message_builder.create_card',
  messageBuilderCreateCustom: 'message_builder.create_custom',
  messageBuilderCreateEmoji: 'message_builder.create_emoji',
  messageBuilderCreateFile: 'message_builder.create_file',
  messageBuilderCreateForward: 'message_builder.create_forward',
  messageBuilderCreateImage: 'message_builder.create_image',
  messageBuilderCreateImageGroup: 'message_builder.create_image_group',
  messageBuilderCreateLinkCard: 'message_builder.create_link_card',
  messageBuilderCreateLocation: 'message_builder.create_location',
  messageBuilderCreateMiniProgram: 'message_builder.create_mini_program',
  messageBuilderCreateNotification: 'message_builder.create_notification',
  messageBuilderCreatePlaceholder: 'message_builder.create_placeholder',
  messageBuilderCreateQuote: 'message_builder.create_quote',
  messageBuilderCreateRichDoc: 'message_builder.create_rich_doc',
  messageBuilderCreateSchedule: 'message_builder.create_schedule',
  messageBuilderCreateSticker: 'message_builder.create_sticker',
  messageBuilderCreateSystem: 'message_builder.create_system',
  messageBuilderCreateTask: 'message_builder.create_task',
  messageBuilderCreateText: 'message_builder.create_text',
  messageBuilderCreateThreadReply: 'message_builder.create_thread_reply',
  messageBuilderCreateVideo: 'message_builder.create_video',
  messageBuilderCreateVote: 'message_builder.create_vote',
  messageBuilderCreateWithContent: 'message_builder.create_with_content',
  messageCreateText: 'message.create_text',
  messageDispatch: 'message.dispatch',
  messageSendNoOss: 'message.send_no_oss',
  messageSend: 'message.send',
  messageList: 'message.list',
  messageRecall: 'message.recall',
  messageEditTextByMessageId: 'message.edit_text_by_message_id',
  messageDelete: 'message.delete',
  messageDeleteForSelf: 'message.delete_for_self',
  messageDeleteForEveryone: 'message.delete_for_everyone',
  messageMarkReadAndBurn: 'message.mark_read_and_burn',
  messageAddReaction: 'message.add_reaction',
  messageRemoveReaction: 'message.remove_reaction',
  messagePin: 'message.pin',
  messageUnpin: 'message.unpin',
  messagePinByMessageId: 'message.pin_by_message_id',
  messageUnpinByMessageId: 'message.unpin_by_message_id',
  messageMark: 'message.mark',
  messageMarkWithColor: 'message.mark_with_color',
  messageUnmark: 'message.unmark',
  messageMarkByMessageId: 'message.mark_by_message_id',
  messageUnmarkByMessageId: 'message.unmark_by_message_id',
  messageGet: 'message.get',
  messageGetRaw: 'message.get_raw',
  messageSearch: 'message.search',
  messageSearchByQuery: 'message.search_by_query',
  messageSearchInConversation: 'message.search_in_conversation',
  messageEditRichDocByMessageId: 'message.edit_rich_doc_by_message_id',
  messageTyping: 'message.typing',
  syncConversationSummaries: 'sync.conversation_summaries',
  syncConversationSummariesWithVersions: 'sync.conversation_summaries_with_versions',
  syncConversationHistoryBackfill: 'sync.conversation_history_backfill',
  syncConversation: 'sync.conversation',
  syncMessages: 'sync.messages',
  presenceGet: 'presence.get',
  presenceBatchGet: 'presence.batch_get',
  presenceSubscribe: 'presence.subscribe',
  mediaUploadFile: 'media.upload_file',
  mediaUploadImage: 'media.upload_image',
  mediaUploadVideo: 'media.upload_video',
  mediaUploadBytes: 'media.upload_bytes',
  mediaDeleteFile: 'media.delete_file',
  mediaGetUrl: 'media.get_url',
  mediaTempDownloadUrl: 'media.temp_download_url',
  mediaResolveAccess: 'media.resolve_access',
  mediaCacheRemote: 'media.cache_remote',
  mediaCacheStats: 'media.cache_stats',
  mediaSetCacheMaxBytes: 'media.set_cache_max_bytes',
  mediaSetCacheRoot: 'media.set_cache_root',
  mediaClearCache: 'media.clear_cache',
  mediaUserDownloadGetSubfolder: 'media.user_download_get_subfolder',
  mediaUserDownloadSetSubfolder: 'media.user_download_set_subfolder',
  mediaUserDownloadGetSavedPath: 'media.user_download_get_saved_path',
  mediaUserDownloadDeleteRecord: 'media.user_download_delete_record',
  mediaCancelUserFileDownload: 'media.cancel_user_file_download',
  mediaDownloadFileToDownloads: 'media.download_file_to_downloads',
  capabilityList: 'capability.list',
  capabilityListUser: 'capability.list_user',
  capabilityDispatch: 'capability.dispatch',
  capabilityGrant: 'capability.grant',
  capabilityRevoke: 'capability.revoke',
  capabilitySendCallSignal: 'capability.send_call_signal',
  eventSubscribe: 'event.subscribe',
  eventSubscribeBatch: 'event.subscribe_batch',
  eventUnsubscribe: 'event.unsubscribe',
  eventUnsubscribeAll: 'event.unsubscribe_all',
  diagnosticsSdkVersion: 'diagnostics.sdk_version',
  diagnosticsFfiContractVersion: 'diagnostics.ffi_contract_version',
  diagnosticsDataRoot: 'diagnostics.data_root',
  diagnosticsRuntimeHealth: 'diagnostics.runtime_health',
} as const;

/** Event constants grouped by source domain in the generated key names. */
export const SdkEvents = {
  lifecycleInitializing: 'initializing',
  lifecycleInitialized: 'initialized',
  lifecycleInitFailed: 'init_failed',
  lifecycleLoginSucceeded: 'login_succeeded',
  lifecycleLoginFailed: 'login_failed',
  lifecycleLoggedOut: 'logged_out',
  lifecycleDisposed: 'disposed',
  connectionConnecting: 'connecting',
  connectionConnected: 'connected',
  connectionDisconnected: 'disconnected',
  connectionReconnecting: 'reconnecting',
  connectionReconnectFailed: 'reconnect_failed',
  connectionReady: 'ready',
  connectionStateChanged: 'state_changed',
  connectionSyncStateChanged: 'sync_state_changed',
  connectionServerError: 'server_error',
  connectionKickedOff: 'kicked_off',
  connectionTokenExpired: 'token_expired',
  messageReceived: 'received',
  messageReceivedBatch: 'received_batch',
  messageSendAck: 'send_ack',
  messageSendFailed: 'send_failed',
  messageCapability: 'capability',
  messageRecalled: 'recalled',
  messageEdited: 'edited',
  messageDeleted: 'deleted',
  messageReadReceipt: 'read_receipt',
  messageReactionChanged: 'reaction_changed',
  messageTyping: 'typing',
  messageBurnScheduled: 'burn_scheduled',
  messageBurned: 'burned',
  messageHardDeleted: 'hard_deleted',
  messagePinned: 'pinned',
  messageUnpinned: 'unpinned',
  messageMarked: 'marked',
  messageUnmarked: 'unmarked',
  messageRetentionScheduled: 'retention_scheduled',
  messageRetentionExpired: 'retention_expired',
  messageRetentionPurged: 'retention_purged',
  messagePresenceChanged: 'presence_changed',
  messageCallSignal: 'call_signal',
  messageCustom: 'custom',
  conversationCreated: 'created',
  conversationUpdated: 'updated',
  conversationDeleted: 'deleted',
  conversationUnreadCountChanged: 'unread_count_changed',
  conversationSynced: 'synced',
  syncStateChanged: 'state_changed',
  syncStarted: 'started',
  syncFinished: 'finished',
  syncFailed: 'failed',
  syncProgress: 'progress',
  syncTaskCompleted: 'task_completed',
  syncResyncNeeded: 'resync_needed',
  notificationReceived: 'received',
  extensionEvent: 'event',
  presenceChanged: 'changed',
  mediaCacheChanged: 'cache_changed',
  mediaUploadProgress: 'upload_progress',
  mediaDownloadProgress: 'download_progress',
  capabilityChanged: 'changed',
  capabilityUnavailable: 'unavailable',
} as const;
