package com.flare.im.model.event.message

/** GENERATED. Do not edit by hand. */
/** Message event notification name. */
enum class MessageEventName { RECEIVED, RECEIVED_BATCH, SEND_ACK, SEND_FAILED, CAPABILITY, RECALLED, TYPING, TYPING_AGGREGATE, EDITED, REACTION_CHANGED, DELETED, READ_RECEIPT, BURN_SCHEDULED, BURNED, HARD_DELETED, PINNED, UNPINNED, MARKED, UNMARKED, RETENTION_SCHEDULED, RETENTION_EXPIRED, RETENTION_PURGED, PRESENCE_CHANGED, CALL_SIGNAL, CUSTOM }
