import Foundation

/// GENERATED. Do not edit by hand.
/// Describes how one SDK operation reaches the native layer.
public struct NativeCallDescriptor: Sendable {
    public let module: String
    public let method: String
    public let operation: String
    public let transport: String
    public let cApi: String
    public let dispatchOp: String?
    public let requestEncoding: String
    public let responseEncoding: String
    public let returnMode: String
    public let callback: String?
    public let handlePolicy: String
}

/// Platform runtimes implement this bridge using FFI, JNI, N-API, WASM or host IPC.
public protocol NativeBridgeProtocol: AnyObject {
    func invoke(_ descriptor: NativeCallDescriptor, request: AnySendable?) async throws -> AnySendable
}

public enum NativeCallMap {
    /// create maps to `flare_sdk_create` via `ffi-symbol`. Operation: `sdk.create`.
    public static let sdkCreate = NativeCallDescriptor(module: "session", method: "create", operation: "sdk.create", transport: "ffi-symbol", cApi: "flare_sdk_create", dispatchOp: nil, requestEncoding: "none", responseEncoding: "handle", returnMode: "sync", callback: nil, handlePolicy: "create-handle")
    /// init maps to `flare_sdk_init` via `ffi-symbol`. Operation: `sdk.init`.
    public static let sdkInit = NativeCallDescriptor(module: "session", method: "init", operation: "sdk.init", transport: "ffi-symbol", cApi: "flare_sdk_init", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// uninit maps to `flare_sdk_uninit` via `ffi-symbol`. Operation: `sdk.uninit`.
    public static let sdkUninit = NativeCallDescriptor(module: "session", method: "uninit", operation: "sdk.uninit", transport: "ffi-symbol", cApi: "flare_sdk_uninit", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// login maps to `flare_sdk_login` via `ffi-symbol`. Operation: `sdk.login`.
    public static let sdkLogin = NativeCallDescriptor(module: "session", method: "login", operation: "sdk.login", transport: "ffi-symbol", cApi: "flare_sdk_login", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// prepare maps to `flare_sdk_prepare` via `ffi-symbol`. Operation: `sdk.prepare`.
    public static let sdkPrepare = NativeCallDescriptor(module: "session", method: "prepare", operation: "sdk.prepare", transport: "ffi-symbol", cApi: "flare_sdk_prepare", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// connect maps to `flare_sdk_connect` via `ffi-symbol`. Operation: `sdk.connect`.
    public static let sdkConnect = NativeCallDescriptor(module: "session", method: "connect", operation: "sdk.connect", transport: "ffi-symbol", cApi: "flare_sdk_connect", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// updateAccessToken maps to `flare_sdk_update_access_token` via `ffi-symbol`. Operation: `sdk.update_access_token`.
    public static let sdkUpdateAccessToken = NativeCallDescriptor(module: "session", method: "updateAccessToken", operation: "sdk.update_access_token", transport: "ffi-symbol", cApi: "flare_sdk_update_access_token", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setHeartbeatAppState maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sdk.set_heartbeat_app_state`.
    public static let sdkSetHeartbeatAppState = NativeCallDescriptor(module: "session", method: "setHeartbeatAppState", operation: "sdk.set_heartbeat_app_state", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setHeartbeatNatTimeout maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sdk.set_heartbeat_nat_timeout`.
    public static let sdkSetHeartbeatNatTimeout = NativeCallDescriptor(module: "session", method: "setHeartbeatNatTimeout", operation: "sdk.set_heartbeat_nat_timeout", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// heartbeatEffectiveInterval maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sdk.heartbeat_effective_interval`.
    public static let sdkHeartbeatEffectiveInterval = NativeCallDescriptor(module: "session", method: "heartbeatEffectiveInterval", operation: "sdk.heartbeat_effective_interval", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// logout maps to `flare_sdk_logout` via `ffi-symbol`. Operation: `sdk.logout`.
    public static let sdkLogout = NativeCallDescriptor(module: "session", method: "logout", operation: "sdk.logout", transport: "ffi-symbol", cApi: "flare_sdk_logout", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// dispose maps to `flare_sdk_release` via `ffi-symbol`. Operation: `sdk.dispose`.
    public static let sdkDispose = NativeCallDescriptor(module: "session", method: "dispose", operation: "sdk.dispose", transport: "ffi-symbol", cApi: "flare_sdk_release", dispatchOp: nil, requestEncoding: "handle", responseEncoding: "unit", returnMode: "sync", callback: nil, handlePolicy: "release-handle")
    /// hardReset maps to `flare_sdk_hard_reset` via `ffi-symbol`. Operation: `sdk.hard_reset`.
    public static let sdkHardReset = NativeCallDescriptor(module: "session", method: "hardReset", operation: "sdk.hard_reset", transport: "ffi-symbol", cApi: "flare_sdk_hard_reset", dispatchOp: nil, requestEncoding: "none", responseEncoding: "unit", returnMode: "sync", callback: nil, handlePolicy: "reset-process")
    /// currentUserId maps to `flare_sdk_current_user_id` via `ffi-symbol`. Operation: `sdk.current_user_id`.
    public static let sdkCurrentUserId = NativeCallDescriptor(module: "session", method: "currentUserId", operation: "sdk.current_user_id", transport: "ffi-symbol", cApi: "flare_sdk_current_user_id", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// isConnected maps to `flare_sdk_is_connected` via `ffi-symbol`. Operation: `sdk.is_connected`.
    public static let sdkIsConnected = NativeCallDescriptor(module: "session", method: "isConnected", operation: "sdk.is_connected", transport: "ffi-symbol", cApi: "flare_sdk_is_connected", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "boolean", returnMode: "sync", callback: nil, handlePolicy: "client-handle")
    /// sessionActive maps to `flare_sdk_session_active` via `ffi-symbol`. Operation: `sdk.session_active`.
    public static let sdkSessionActive = NativeCallDescriptor(module: "session", method: "sessionActive", operation: "sdk.session_active", transport: "ffi-symbol", cApi: "flare_sdk_session_active", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "boolean", returnMode: "sync", callback: nil, handlePolicy: "client-handle")
    /// getConnectionState maps to `flare_sdk_state` via `ffi-symbol`. Operation: `connection.get_state`.
    public static let connectionGetState = NativeCallDescriptor(module: "connection", method: "getConnectionState", operation: "connection.get_state", transport: "ffi-symbol", cApi: "flare_sdk_state", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "enum", returnMode: "sync", callback: nil, handlePolicy: "client-handle")
    /// disconnect maps to `flare_sdk_disconnect` via `ffi-symbol`. Operation: `connection.disconnect`.
    public static let connectionDisconnect = NativeCallDescriptor(module: "connection", method: "disconnect", operation: "connection.disconnect", transport: "ffi-symbol", cApi: "flare_sdk_disconnect", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// notifyNetworkChange maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `connection.notify_network_change`.
    public static let connectionNotifyNetworkChange = NativeCallDescriptor(module: "connection", method: "notifyNetworkChange", operation: "connection.notify_network_change", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listConversations maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list`.
    public static let conversationList = NativeCallDescriptor(module: "conversations", method: "listConversations", operation: "conversation.list", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listConversationsByQuery maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_by_query`.
    public static let conversationListByQuery = NativeCallDescriptor(module: "conversations", method: "listConversationsByQuery", operation: "conversation.list_by_query", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listConversationsIncludingArchived maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_including_archived`.
    public static let conversationListIncludingArchived = NativeCallDescriptor(module: "conversations", method: "listConversationsIncludingArchived", operation: "conversation.list_including_archived", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getConversation maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get`.
    public static let conversationGet = NativeCallDescriptor(module: "conversations", method: "getConversation", operation: "conversation.get", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getOneConversation maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get_one`.
    public static let conversationGetOne = NativeCallDescriptor(module: "conversations", method: "getOneConversation", operation: "conversation.get_one", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getGroupConversationByUserIds maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get_group_by_user_ids`.
    public static let conversationGetGroupByUserIds = NativeCallDescriptor(module: "conversations", method: "getGroupConversationByUserIds", operation: "conversation.get_group_by_user_ids", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getMultipleConversations maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.get_multiple`.
    public static let conversationGetMultiple = NativeCallDescriptor(module: "conversations", method: "getMultipleConversations", operation: "conversation.get_multiple", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listConversationsPaginated maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_paginated`.
    public static let conversationListPaginated = NativeCallDescriptor(module: "conversations", method: "listConversationsPaginated", operation: "conversation.list_paginated", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listRawConversations maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.list_raw`.
    public static let conversationListRaw = NativeCallDescriptor(module: "conversations", method: "listRawConversations", operation: "conversation.list_raw", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// bootstrapHomeTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.bootstrap_home`.
    public static let conversationBootstrapHome = NativeCallDescriptor(module: "conversations", method: "bootstrapHomeTimeline", operation: "conversation.bootstrap_home", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// openConversationTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.open_timeline`.
    public static let conversationOpenTimeline = NativeCallDescriptor(module: "conversations", method: "openConversationTimeline", operation: "conversation.open_timeline", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// markConversationRead maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.mark_read`.
    public static let conversationMarkRead = NativeCallDescriptor(module: "conversations", method: "markConversationRead", operation: "conversation.mark_read", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setConversationPinned maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.set_pinned`.
    public static let conversationSetPinned = NativeCallDescriptor(module: "conversations", method: "setConversationPinned", operation: "conversation.set_pinned", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setConversationMuted maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.set_muted`.
    public static let conversationSetMuted = NativeCallDescriptor(module: "conversations", method: "setConversationMuted", operation: "conversation.set_muted", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setConversationArchived maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.set_archived`.
    public static let conversationSetArchived = NativeCallDescriptor(module: "conversations", method: "setConversationArchived", operation: "conversation.set_archived", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// markConversationUnread maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.mark_unread`.
    public static let conversationMarkUnread = NativeCallDescriptor(module: "conversations", method: "markConversationUnread", operation: "conversation.mark_unread", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// deleteConversation maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.delete`.
    public static let conversationDelete = NativeCallDescriptor(module: "conversations", method: "deleteConversation", operation: "conversation.delete", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// updateConversationDraft maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.update_draft`.
    public static let conversationUpdateDraft = NativeCallDescriptor(module: "conversations", method: "updateConversationDraft", operation: "conversation.update_draft", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// clearLocalChatHistory maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `conversation.clear_local_chat_history`.
    public static let conversationClearLocalChatHistory = NativeCallDescriptor(module: "conversations", method: "clearLocalChatHistory", operation: "conversation.clear_local_chat_history", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listSupportedBuildOperations maps to `flare_message_build_json` via `catalog-static`. Operation: `message_builder.list_catalog`.
    public static let messageBuilderListCatalog = NativeCallDescriptor(module: "message_builder", method: "listSupportedBuildOperations", operation: "message_builder.list_catalog", transport: "catalog-static", cApi: "flare_message_build_json", dispatchOp: nil, requestEncoding: "local-static", responseEncoding: "json-object", returnMode: "local", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// normalizeRichDocFromMarkdown maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `rich_doc_v2.normalize_from_markdown`.
    public static let richDocV2NormalizeFromMarkdown = NativeCallDescriptor(module: "message_builder", method: "normalizeRichDocFromMarkdown", operation: "rich_doc_v2.normalize_from_markdown", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// normalizeRichDocFromHtml maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `rich_doc_v2.normalize_from_html`.
    public static let richDocV2NormalizeFromHtml = NativeCallDescriptor(module: "message_builder", method: "normalizeRichDocFromHtml", operation: "rich_doc_v2.normalize_from_html", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// normalizeRichDocFromDocJson maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `rich_doc_v2.normalize_from_doc_json`.
    public static let richDocV2NormalizeFromDocJson = NativeCallDescriptor(module: "message_builder", method: "normalizeRichDocFromDocJson", operation: "rich_doc_v2.normalize_from_doc_json", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildAnnouncement maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_announcement`. Operation: `message_builder.create_announcement`.
    public static let messageBuilderCreateAnnouncement = NativeCallDescriptor(module: "message_builder", method: "buildAnnouncement", operation: "message_builder.create_announcement", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_announcement", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildAudio maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_audio`. Operation: `message_builder.create_audio`.
    public static let messageBuilderCreateAudio = NativeCallDescriptor(module: "message_builder", method: "buildAudio", operation: "message_builder.create_audio", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_audio", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildCard maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_card`. Operation: `message_builder.create_card`.
    public static let messageBuilderCreateCard = NativeCallDescriptor(module: "message_builder", method: "buildCard", operation: "message_builder.create_card", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_card", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildCustom maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_custom`. Operation: `message_builder.create_custom`.
    public static let messageBuilderCreateCustom = NativeCallDescriptor(module: "message_builder", method: "buildCustom", operation: "message_builder.create_custom", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_custom", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildEmoji maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_emoji`. Operation: `message_builder.create_emoji`.
    public static let messageBuilderCreateEmoji = NativeCallDescriptor(module: "message_builder", method: "buildEmoji", operation: "message_builder.create_emoji", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_emoji", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildFile maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_file`. Operation: `message_builder.create_file`.
    public static let messageBuilderCreateFile = NativeCallDescriptor(module: "message_builder", method: "buildFile", operation: "message_builder.create_file", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_file", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildForward maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_forward`. Operation: `message_builder.create_forward`.
    public static let messageBuilderCreateForward = NativeCallDescriptor(module: "message_builder", method: "buildForward", operation: "message_builder.create_forward", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_forward", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildImage maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_image`. Operation: `message_builder.create_image`.
    public static let messageBuilderCreateImage = NativeCallDescriptor(module: "message_builder", method: "buildImage", operation: "message_builder.create_image", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_image", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildImageGroup maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_image_group`. Operation: `message_builder.create_image_group`.
    public static let messageBuilderCreateImageGroup = NativeCallDescriptor(module: "message_builder", method: "buildImageGroup", operation: "message_builder.create_image_group", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_image_group", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildLinkCard maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_link_card`. Operation: `message_builder.create_link_card`.
    public static let messageBuilderCreateLinkCard = NativeCallDescriptor(module: "message_builder", method: "buildLinkCard", operation: "message_builder.create_link_card", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_link_card", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildLocation maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_location`. Operation: `message_builder.create_location`.
    public static let messageBuilderCreateLocation = NativeCallDescriptor(module: "message_builder", method: "buildLocation", operation: "message_builder.create_location", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_location", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildMiniProgram maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_mini_program`. Operation: `message_builder.create_mini_program`.
    public static let messageBuilderCreateMiniProgram = NativeCallDescriptor(module: "message_builder", method: "buildMiniProgram", operation: "message_builder.create_mini_program", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_mini_program", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildNotification maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_notification`. Operation: `message_builder.create_notification`.
    public static let messageBuilderCreateNotification = NativeCallDescriptor(module: "message_builder", method: "buildNotification", operation: "message_builder.create_notification", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_notification", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildPlaceholder maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_placeholder`. Operation: `message_builder.create_placeholder`.
    public static let messageBuilderCreatePlaceholder = NativeCallDescriptor(module: "message_builder", method: "buildPlaceholder", operation: "message_builder.create_placeholder", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_placeholder", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildQuote maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_quote`. Operation: `message_builder.create_quote`.
    public static let messageBuilderCreateQuote = NativeCallDescriptor(module: "message_builder", method: "buildQuote", operation: "message_builder.create_quote", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_quote", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildRichDoc maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_rich_doc`. Operation: `message_builder.create_rich_doc`.
    public static let messageBuilderCreateRichDoc = NativeCallDescriptor(module: "message_builder", method: "buildRichDoc", operation: "message_builder.create_rich_doc", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_rich_doc", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildSchedule maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_schedule`. Operation: `message_builder.create_schedule`.
    public static let messageBuilderCreateSchedule = NativeCallDescriptor(module: "message_builder", method: "buildSchedule", operation: "message_builder.create_schedule", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_schedule", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildSticker maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_sticker`. Operation: `message_builder.create_sticker`.
    public static let messageBuilderCreateSticker = NativeCallDescriptor(module: "message_builder", method: "buildSticker", operation: "message_builder.create_sticker", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_sticker", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildSystem maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_system`. Operation: `message_builder.create_system`.
    public static let messageBuilderCreateSystem = NativeCallDescriptor(module: "message_builder", method: "buildSystem", operation: "message_builder.create_system", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_system", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildTask maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_task`. Operation: `message_builder.create_task`.
    public static let messageBuilderCreateTask = NativeCallDescriptor(module: "message_builder", method: "buildTask", operation: "message_builder.create_task", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_task", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildText maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_text`. Operation: `message_builder.create_text`.
    public static let messageBuilderCreateText = NativeCallDescriptor(module: "message_builder", method: "buildText", operation: "message_builder.create_text", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_text", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildThreadReply maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_thread_reply`. Operation: `message_builder.create_thread_reply`.
    public static let messageBuilderCreateThreadReply = NativeCallDescriptor(module: "message_builder", method: "buildThreadReply", operation: "message_builder.create_thread_reply", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_thread_reply", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildVideo maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_video`. Operation: `message_builder.create_video`.
    public static let messageBuilderCreateVideo = NativeCallDescriptor(module: "message_builder", method: "buildVideo", operation: "message_builder.create_video", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_video", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildVote maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_vote`. Operation: `message_builder.create_vote`.
    public static let messageBuilderCreateVote = NativeCallDescriptor(module: "message_builder", method: "buildVote", operation: "message_builder.create_vote", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_vote", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// buildWithContent maps to `flare_message_build_json` via `dispatch-json`, dispatch op `create_with_content`. Operation: `message_builder.create_with_content`.
    public static let messageBuilderCreateWithContent = NativeCallDescriptor(module: "message_builder", method: "buildWithContent", operation: "message_builder.create_with_content", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: "create_with_content", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// createTextMessage maps to `flare_message_create_text` via `ffi-symbol`. Operation: `message.create_text`.
    public static let messageCreateText = NativeCallDescriptor(module: "messages", method: "createTextMessage", operation: "message.create_text", transport: "ffi-symbol", cApi: "flare_message_create_text", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// dispatchMessage maps to `flare_message_dispatch_json` via `dispatch-json`. Operation: `message.dispatch`.
    public static let messageDispatch = NativeCallDescriptor(module: "messages", method: "dispatchMessage", operation: "message.dispatch", transport: "dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// sendMessageNoOss maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `send_no_oss`. Operation: `message.send_no_oss`.
    public static let messageSendNoOss = NativeCallDescriptor(module: "messages", method: "sendMessageNoOss", operation: "message.send_no_oss", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "send_no_oss", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// sendMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `send`. Operation: `message.send`.
    public static let messageSend = NativeCallDescriptor(module: "messages", method: "sendMessage", operation: "message.send", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "send", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listMessages maps to `flare_message_list` via `ffi-symbol`. Operation: `message.list`.
    public static let messageList = NativeCallDescriptor(module: "messages", method: "listMessages", operation: "message.list", transport: "ffi-symbol", cApi: "flare_message_list", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// recallMessage maps to `flare_message_recall` via `ffi-symbol`. Operation: `message.recall`.
    public static let messageRecall = NativeCallDescriptor(module: "messages", method: "recallMessage", operation: "message.recall", transport: "ffi-symbol", cApi: "flare_message_recall", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// editTextByMessageId maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `edit_text_by_message_id`. Operation: `message.edit_text_by_message_id`.
    public static let messageEditTextByMessageId = NativeCallDescriptor(module: "messages", method: "editTextByMessageId", operation: "message.edit_text_by_message_id", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "edit_text_by_message_id", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// deleteMessage maps to `flare_message_delete` via `ffi-symbol`. Operation: `message.delete`.
    public static let messageDelete = NativeCallDescriptor(module: "messages", method: "deleteMessage", operation: "message.delete", transport: "ffi-symbol", cApi: "flare_message_delete", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// deleteMessageForSelf maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `delete_for_self`. Operation: `message.delete_for_self`.
    public static let messageDeleteForSelf = NativeCallDescriptor(module: "messages", method: "deleteMessageForSelf", operation: "message.delete_for_self", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "delete_for_self", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// deleteMessageForEveryone maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `delete_for_everyone`. Operation: `message.delete_for_everyone`.
    public static let messageDeleteForEveryone = NativeCallDescriptor(module: "messages", method: "deleteMessageForEveryone", operation: "message.delete_for_everyone", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "delete_for_everyone", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// markMessageReadAndBurn maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark_read_and_burn`. Operation: `message.mark_read_and_burn`.
    public static let messageMarkReadAndBurn = NativeCallDescriptor(module: "messages", method: "markMessageReadAndBurn", operation: "message.mark_read_and_burn", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "mark_read_and_burn", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// addReaction maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `add_reaction`. Operation: `message.add_reaction`.
    public static let messageAddReaction = NativeCallDescriptor(module: "messages", method: "addReaction", operation: "message.add_reaction", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "add_reaction", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// removeReaction maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `remove_reaction`. Operation: `message.remove_reaction`.
    public static let messageRemoveReaction = NativeCallDescriptor(module: "messages", method: "removeReaction", operation: "message.remove_reaction", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "remove_reaction", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// pinMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `pin`. Operation: `message.pin`.
    public static let messagePin = NativeCallDescriptor(module: "messages", method: "pinMessage", operation: "message.pin", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "pin", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// unpinMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unpin`. Operation: `message.unpin`.
    public static let messageUnpin = NativeCallDescriptor(module: "messages", method: "unpinMessage", operation: "message.unpin", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "unpin", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// pinMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `pin_by_message_id`. Operation: `message.pin_by_message_id`.
    public static let messagePinByMessageId = NativeCallDescriptor(module: "messages", method: "pinMessageById", operation: "message.pin_by_message_id", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "pin_by_message_id", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// unpinMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unpin_by_message_id`. Operation: `message.unpin_by_message_id`.
    public static let messageUnpinByMessageId = NativeCallDescriptor(module: "messages", method: "unpinMessageById", operation: "message.unpin_by_message_id", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "unpin_by_message_id", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// markMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark`. Operation: `message.mark`.
    public static let messageMark = NativeCallDescriptor(module: "messages", method: "markMessage", operation: "message.mark", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "mark", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// markMessageWithColor maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark_with_color`. Operation: `message.mark_with_color`.
    public static let messageMarkWithColor = NativeCallDescriptor(module: "messages", method: "markMessageWithColor", operation: "message.mark_with_color", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "mark_with_color", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// unmarkMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unmark`. Operation: `message.unmark`.
    public static let messageUnmark = NativeCallDescriptor(module: "messages", method: "unmarkMessage", operation: "message.unmark", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "unmark", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// markMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `mark_by_message_id`. Operation: `message.mark_by_message_id`.
    public static let messageMarkByMessageId = NativeCallDescriptor(module: "messages", method: "markMessageById", operation: "message.mark_by_message_id", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "mark_by_message_id", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// unmarkMessageById maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `unmark_by_message_id`. Operation: `message.unmark_by_message_id`.
    public static let messageUnmarkByMessageId = NativeCallDescriptor(module: "messages", method: "unmarkMessageById", operation: "message.unmark_by_message_id", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "unmark_by_message_id", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `get`. Operation: `message.get`.
    public static let messageGet = NativeCallDescriptor(module: "messages", method: "getMessage", operation: "message.get", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "get", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getRawMessage maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `get_raw`. Operation: `message.get_raw`.
    public static let messageGetRaw = NativeCallDescriptor(module: "messages", method: "getRawMessage", operation: "message.get_raw", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "get_raw", requestEncoding: "json", responseEncoding: "json", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// searchMessages maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `search`. Operation: `message.search`.
    public static let messageSearch = NativeCallDescriptor(module: "messages", method: "searchMessages", operation: "message.search", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "search", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// searchMessagesByQuery maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `search_by_query`. Operation: `message.search_by_query`.
    public static let messageSearchByQuery = NativeCallDescriptor(module: "messages", method: "searchMessagesByQuery", operation: "message.search_by_query", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "search_by_query", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// searchMessagesInConversation maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `search_in_conversation`. Operation: `message.search_in_conversation`.
    public static let messageSearchInConversation = NativeCallDescriptor(module: "messages", method: "searchMessagesInConversation", operation: "message.search_in_conversation", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "search_in_conversation", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// editRichDocByMessageId maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `edit_rich_doc_by_message_id`. Operation: `message.edit_rich_doc_by_message_id`.
    public static let messageEditRichDocByMessageId = NativeCallDescriptor(module: "messages", method: "editRichDocByMessageId", operation: "message.edit_rich_doc_by_message_id", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "edit_rich_doc_by_message_id", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setTyping maps to `flare_message_dispatch_json` via `message-dispatch-json`, dispatch op `typing`. Operation: `message.typing`.
    public static let messageTyping = NativeCallDescriptor(module: "messages", method: "setTyping", operation: "message.typing", transport: "message-dispatch-json", cApi: "flare_message_dispatch_json", dispatchOp: "typing", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// syncConversationSummaries maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.conversation_summaries`.
    public static let syncConversationSummaries = NativeCallDescriptor(module: "sync", method: "syncConversationSummaries", operation: "sync.conversation_summaries", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// syncConversationSummariesWithVersions maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.conversation_summaries_with_versions`.
    public static let syncConversationSummariesWithVersions = NativeCallDescriptor(module: "sync", method: "syncConversationSummariesWithVersions", operation: "sync.conversation_summaries_with_versions", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// bootstrapStartupHome maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.bootstrap_startup_home`.
    public static let syncBootstrapStartupHome = NativeCallDescriptor(module: "sync", method: "bootstrapStartupHome", operation: "sync.bootstrap_startup_home", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// backfillConversationHistory maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `sync.conversation_history_backfill`.
    public static let syncConversationHistoryBackfill = NativeCallDescriptor(module: "sync", method: "backfillConversationHistory", operation: "sync.conversation_history_backfill", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// syncConversation maps to `flare_sdk_sync_conversation` via `ffi-symbol`. Operation: `sync.conversation`.
    public static let syncConversation = NativeCallDescriptor(module: "sync", method: "syncConversation", operation: "sync.conversation", transport: "ffi-symbol", cApi: "flare_sdk_sync_conversation", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// syncMessages maps to `flare_sdk_sync_messages` via `ffi-symbol`. Operation: `sync.messages`.
    public static let syncMessages = NativeCallDescriptor(module: "sync", method: "syncMessages", operation: "sync.messages", transport: "ffi-symbol", cApi: "flare_sdk_sync_messages", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// upsertUserProfiles maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `user.upsert_profiles`.
    public static let userUpsertProfiles = NativeCallDescriptor(module: "user", method: "upsertUserProfiles", operation: "user.upsert_profiles", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getUserPresence maps to `flare_sdk_get_user_presence` via `ffi-symbol`. Operation: `presence.get`.
    public static let presenceGet = NativeCallDescriptor(module: "presence", method: "getUserPresence", operation: "presence.get", transport: "ffi-symbol", cApi: "flare_sdk_get_user_presence", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// batchGetUserPresence maps to `flare_sdk_batch_get_user_presence` via `ffi-symbol`. Operation: `presence.batch_get`.
    public static let presenceBatchGet = NativeCallDescriptor(module: "presence", method: "batchGetUserPresence", operation: "presence.batch_get", transport: "ffi-symbol", cApi: "flare_sdk_batch_get_user_presence", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// subscribeUserPresence maps to `flare_sdk_subscribe_user_presence` via `ffi-symbol`. Operation: `presence.subscribe`.
    public static let presenceSubscribe = NativeCallDescriptor(module: "presence", method: "subscribeUserPresence", operation: "presence.subscribe", transport: "ffi-symbol", cApi: "flare_sdk_subscribe_user_presence", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// uploadFile maps to `flare_media_upload_file` via `ffi-symbol`. Operation: `media.upload_file`.
    public static let mediaUploadFile = NativeCallDescriptor(module: "media", method: "uploadFile", operation: "media.upload_file", transport: "ffi-symbol", cApi: "flare_media_upload_file", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// uploadImage maps to `flare_media_upload_image` via `ffi-symbol`. Operation: `media.upload_image`.
    public static let mediaUploadImage = NativeCallDescriptor(module: "media", method: "uploadImage", operation: "media.upload_image", transport: "ffi-symbol", cApi: "flare_media_upload_image", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// uploadVideo maps to `flare_media_upload_video` via `ffi-symbol`. Operation: `media.upload_video`.
    public static let mediaUploadVideo = NativeCallDescriptor(module: "media", method: "uploadVideo", operation: "media.upload_video", transport: "ffi-symbol", cApi: "flare_media_upload_video", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// uploadBytes maps to `flare_media_upload_bytes` via `ffi-symbol`. Operation: `media.upload_bytes`.
    public static let mediaUploadBytes = NativeCallDescriptor(module: "media", method: "uploadBytes", operation: "media.upload_bytes", transport: "ffi-symbol", cApi: "flare_media_upload_bytes", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// deleteFile maps to `flare_media_delete_file` via `ffi-symbol`. Operation: `media.delete_file`.
    public static let mediaDeleteFile = NativeCallDescriptor(module: "media", method: "deleteFile", operation: "media.delete_file", transport: "ffi-symbol", cApi: "flare_media_delete_file", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getMediaUrl maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `get_url`. Operation: `media.get_url`.
    public static let mediaGetUrl = NativeCallDescriptor(module: "media", method: "getMediaUrl", operation: "media.get_url", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "get_url", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getTempDownloadUrl maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `temp_download_url`. Operation: `media.temp_download_url`.
    public static let mediaTempDownloadUrl = NativeCallDescriptor(module: "media", method: "getTempDownloadUrl", operation: "media.temp_download_url", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "temp_download_url", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// resolveMediaAccess maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `resolve_access`. Operation: `media.resolve_access`.
    public static let mediaResolveAccess = NativeCallDescriptor(module: "media", method: "resolveMediaAccess", operation: "media.resolve_access", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "resolve_access", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// cacheRemoteMedia maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `cache_remote`. Operation: `media.cache_remote`.
    public static let mediaCacheRemote = NativeCallDescriptor(module: "media", method: "cacheRemoteMedia", operation: "media.cache_remote", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "cache_remote", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getMediaCacheStats maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `cache_stats`. Operation: `media.cache_stats`.
    public static let mediaCacheStats = NativeCallDescriptor(module: "media", method: "getMediaCacheStats", operation: "media.cache_stats", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "cache_stats", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setMediaCacheMaxBytes maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `set_cache_max_bytes`. Operation: `media.set_cache_max_bytes`.
    public static let mediaSetCacheMaxBytes = NativeCallDescriptor(module: "media", method: "setMediaCacheMaxBytes", operation: "media.set_cache_max_bytes", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "set_cache_max_bytes", requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setMediaCacheRoot maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `set_cache_root`. Operation: `media.set_cache_root`.
    public static let mediaSetCacheRoot = NativeCallDescriptor(module: "media", method: "setMediaCacheRoot", operation: "media.set_cache_root", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "set_cache_root", requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// clearMediaCache maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `clear_cache`. Operation: `media.clear_cache`.
    public static let mediaClearCache = NativeCallDescriptor(module: "media", method: "clearMediaCache", operation: "media.clear_cache", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "clear_cache", requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getUserDownloadSubfolder maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_get_subfolder`. Operation: `media.user_download_get_subfolder`.
    public static let mediaUserDownloadGetSubfolder = NativeCallDescriptor(module: "media", method: "getUserDownloadSubfolder", operation: "media.user_download_get_subfolder", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "user_download_get_subfolder", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// setUserDownloadSubfolder maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_set_subfolder`. Operation: `media.user_download_set_subfolder`.
    public static let mediaUserDownloadSetSubfolder = NativeCallDescriptor(module: "media", method: "setUserDownloadSubfolder", operation: "media.user_download_set_subfolder", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "user_download_set_subfolder", requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getUserDownloadSavedPath maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_get_saved_path`. Operation: `media.user_download_get_saved_path`.
    public static let mediaUserDownloadGetSavedPath = NativeCallDescriptor(module: "media", method: "getUserDownloadSavedPath", operation: "media.user_download_get_saved_path", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "user_download_get_saved_path", requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// deleteUserDownloadRecord maps to `flare_media_dispatch_json` via `media-dispatch-json`, dispatch op `user_download_delete_record`. Operation: `media.user_download_delete_record`.
    public static let mediaUserDownloadDeleteRecord = NativeCallDescriptor(module: "media", method: "deleteUserDownloadRecord", operation: "media.user_download_delete_record", transport: "media-dispatch-json", cApi: "flare_media_dispatch_json", dispatchOp: "user_download_delete_record", requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// cancelUserFileDownload maps to `flare_media_cancel_user_file_download` via `ffi-symbol`. Operation: `media.cancel_user_file_download`.
    public static let mediaCancelUserFileDownload = NativeCallDescriptor(module: "media", method: "cancelUserFileDownload", operation: "media.cancel_user_file_download", transport: "ffi-symbol", cApi: "flare_media_cancel_user_file_download", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "boolean", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// downloadFileToDownloads maps to `flare_media_download_file_to_downloads` via `ffi-symbol`. Operation: `media.download_file_to_downloads`.
    public static let mediaDownloadFileToDownloads = NativeCallDescriptor(module: "media", method: "downloadFileToDownloads", operation: "media.download_file_to_downloads", transport: "ffi-symbol", cApi: "flare_media_download_file_to_downloads", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listCapabilities maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_list`. Operation: `capability.list`.
    public static let capabilityList = NativeCallDescriptor(module: "capabilities", method: "listCapabilities", operation: "capability.list", transport: "capability-dispatch-json", cApi: "flare_capability_dispatch_json", dispatchOp: "capability_list", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// listUserCapabilities maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_list_user`. Operation: `capability.list_user`.
    public static let capabilityListUser = NativeCallDescriptor(module: "capabilities", method: "listUserCapabilities", operation: "capability.list_user", transport: "capability-dispatch-json", cApi: "flare_capability_dispatch_json", dispatchOp: "capability_list_user", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// dispatchCapability maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_dispatch`. Operation: `capability.dispatch`.
    public static let capabilityDispatch = NativeCallDescriptor(module: "capabilities", method: "dispatchCapability", operation: "capability.dispatch", transport: "capability-dispatch-json", cApi: "flare_capability_dispatch_json", dispatchOp: "capability_dispatch", requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// grantCapability maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_grant`. Operation: `capability.grant`.
    public static let capabilityGrant = NativeCallDescriptor(module: "capabilities", method: "grantCapability", operation: "capability.grant", transport: "capability-dispatch-json", cApi: "flare_capability_dispatch_json", dispatchOp: "capability_grant", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// revokeCapability maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `capability_revoke`. Operation: `capability.revoke`.
    public static let capabilityRevoke = NativeCallDescriptor(module: "capabilities", method: "revokeCapability", operation: "capability.revoke", transport: "capability-dispatch-json", cApi: "flare_capability_dispatch_json", dispatchOp: "capability_revoke", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// sendCallSignal maps to `flare_capability_dispatch_json` via `capability-dispatch-json`, dispatch op `send_call_signal`. Operation: `capability.send_call_signal`.
    public static let capabilitySendCallSignal = NativeCallDescriptor(module: "capabilities", method: "sendCallSignal", operation: "capability.send_call_signal", transport: "capability-dispatch-json", cApi: "flare_capability_dispatch_json", dispatchOp: "send_call_signal", requestEncoding: "json", responseEncoding: "unit", returnMode: "callback-unit", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// openTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.timeline.open`.
    public static let viewTimelineOpen = NativeCallDescriptor(module: "views", method: "openTimeline", operation: "view.timeline.open", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// loadOlderTimeline maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.timeline.load_older`.
    public static let viewTimelineLoadOlder = NativeCallDescriptor(module: "views", method: "loadOlderTimeline", operation: "view.timeline.load_older", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// openConversationList maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.conversation_list.open`.
    public static let viewConversationListOpen = NativeCallDescriptor(module: "views", method: "openConversationList", operation: "view.conversation_list.open", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// close maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `view.close`.
    public static let viewClose = NativeCallDescriptor(module: "views", method: "close", operation: "view.close", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// subscribeEvents maps to `flare_event_subscribe` via `ffi-symbol`. Operation: `event.subscribe`.
    public static let eventSubscribe = NativeCallDescriptor(module: "events", method: "subscribeEvents", operation: "event.subscribe", transport: "ffi-symbol", cApi: "flare_event_subscribe", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "subscription", returnMode: "event-stream", callback: "FlareEventCallback", handlePolicy: "client-handle")
    /// subscribeEventsBatch maps to `flare_event_subscribe_batch` via `ffi-symbol`. Operation: `event.subscribe_batch`.
    public static let eventSubscribeBatch = NativeCallDescriptor(module: "events", method: "subscribeEventsBatch", operation: "event.subscribe_batch", transport: "ffi-symbol", cApi: "flare_event_subscribe_batch", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "subscription", returnMode: "event-stream", callback: "FlareEventBatchCallback", handlePolicy: "client-handle")
    /// unsubscribe maps to `flare_event_unsubscribe` via `ffi-symbol`. Operation: `event.unsubscribe`.
    public static let eventUnsubscribe = NativeCallDescriptor(module: "events", method: "unsubscribe", operation: "event.unsubscribe", transport: "ffi-symbol", cApi: "flare_event_unsubscribe", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "unit", returnMode: "sync", callback: nil, handlePolicy: "subscription-handle")
    /// unsubscribeAll maps to `flare_event_unsubscribe_all` via `ffi-symbol`. Operation: `event.unsubscribe_all`.
    public static let eventUnsubscribeAll = NativeCallDescriptor(module: "events", method: "unsubscribeAll", operation: "event.unsubscribe_all", transport: "ffi-symbol", cApi: "flare_event_unsubscribe_all", dispatchOp: nil, requestEncoding: "none", responseEncoding: "unit", returnMode: "sync", callback: nil, handlePolicy: "process")
    /// getSdkVersion maps to `flare_sdk_version` via `ffi-symbol`. Operation: `diagnostics.sdk_version`.
    public static let diagnosticsSdkVersion = NativeCallDescriptor(module: "diagnostics", method: "getSdkVersion", operation: "diagnostics.sdk_version", transport: "ffi-symbol", cApi: "flare_sdk_version", dispatchOp: nil, requestEncoding: "none", responseEncoding: "json-object", returnMode: "sync-string", callback: nil, handlePolicy: "process")
    /// getFfiContractVersion maps to `flare_sdk_ffi_contract_version` via `ffi-symbol`. Operation: `diagnostics.ffi_contract_version`.
    public static let diagnosticsFfiContractVersion = NativeCallDescriptor(module: "diagnostics", method: "getFfiContractVersion", operation: "diagnostics.ffi_contract_version", transport: "ffi-symbol", cApi: "flare_sdk_ffi_contract_version", dispatchOp: nil, requestEncoding: "none", responseEncoding: "json-object", returnMode: "sync-string", callback: nil, handlePolicy: "process")
    /// getDataRoot maps to `flare_sdk_data_root` via `ffi-symbol`. Operation: `diagnostics.data_root`.
    public static let diagnosticsDataRoot = NativeCallDescriptor(module: "diagnostics", method: "getDataRoot", operation: "diagnostics.data_root", transport: "ffi-symbol", cApi: "flare_sdk_data_root", dispatchOp: nil, requestEncoding: "typed-ffi", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// getRuntimeHealth maps to `flare_sdk_invoke_json` via `contract-invoke-json`. Operation: `diagnostics.runtime_health`.
    public static let diagnosticsRuntimeHealth = NativeCallDescriptor(module: "diagnostics", method: "getRuntimeHealth", operation: "diagnostics.runtime_health", transport: "contract-invoke-json", cApi: "flare_sdk_invoke_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
    /// Internal typed message builder dispatch over `flare_message_build_json`.
    public static let messageBuilderDispatch = NativeCallDescriptor(module: "message_builder", method: "dispatchTypedBuild", operation: "message_builder.dispatch", transport: "dispatch-json", cApi: "flare_message_build_json", dispatchOp: nil, requestEncoding: "json", responseEncoding: "json-object", returnMode: "callback", callback: "FlareResultCallback", handlePolicy: "client-handle")
}
