/*
 * Flare IM Core SDK - C ABI Header
 *
 * This file is automatically generated by cbindgen.
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated from Rust source code.
 */


#ifndef FLARE_IM_CORE_SDK_FFI_H
#define FLARE_IM_CORE_SDK_FFI_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C 字符串最大扫描长度（含末尾 NUL 之前），防止恶意/损坏指针拖垮扫描。
 */
#define MAX_CSTRING_BYTES ((4 * 1024) * 1024)

#define FLARE_OK 0

#define FLARE_ERR_INVALID_HANDLE 1

#define FLARE_ERR_INVALID_PARAM 2

#define FLARE_ERR_NOT_CONNECTED 3

#define FLARE_ERR_OPERATION_TIMEOUT 4

#define FLARE_ERR_NETWORK_ERROR 5

#define FLARE_ERR_AUTH_FAILED 6

#define FLARE_ERR_TOKEN_EXPIRED 7

#define FLARE_ERR_INTERNAL 8

#define FLARE_ERR_JSON_PARSE 9

#define FLARE_ERR_NULL_POINTER 10

#define FLARE_ERR_FFI_PANIC 11

#define FLARE_EVENT_UNKNOWN 0

#define FLARE_EVENT_CONNECTION_CONNECTED 1001

#define FLARE_EVENT_CONNECTION_DISCONNECTED 1002

#define FLARE_EVENT_CONNECTION_RECONNECTING 1003

#define FLARE_EVENT_CONNECTION_STATE_CHANGED 1004

#define FLARE_EVENT_CONNECTION_SYNC_STATE_CHANGED 1005

#define FLARE_EVENT_CONNECTION_SERVER_ERROR 1006

#define FLARE_EVENT_CONNECTION_KICKED_OFF 1007

#define FLARE_EVENT_CONNECTION_TOKEN_EXPIRED 1008

#define FLARE_EVENT_MESSAGE_RECEIVED 2001

#define FLARE_EVENT_MESSAGE_RECEIVED_BATCH 2002

#define FLARE_EVENT_MESSAGE_SEND_ACK 2003

#define FLARE_EVENT_MESSAGE_SEND_FAILED 2004

#define FLARE_EVENT_MESSAGE_RECALLED 2005

#define FLARE_EVENT_MESSAGE_TYPING 2006

#define FLARE_EVENT_MESSAGE_CAPABILITY 2007

#define FLARE_EVENT_MESSAGE_EDITED 2008

#define FLARE_EVENT_MESSAGE_REACTION_CHANGED 2009

#define FLARE_EVENT_MESSAGE_DELETED 2010

#define FLARE_EVENT_MESSAGE_READ_RECEIPT 2011

#define FLARE_EVENT_MESSAGE_TYPING_AGGREGATE 2021

#define FLARE_EVENT_MESSAGE_RETENTION_SCHEDULED 2012

#define FLARE_EVENT_MESSAGE_RETENTION_EXPIRED 2013

#define FLARE_EVENT_MESSAGE_RETENTION_PURGED 2014

#define FLARE_EVENT_MESSAGE_PINNED 2015

#define FLARE_EVENT_MESSAGE_UNPINNED 2016

#define FLARE_EVENT_MESSAGE_MARKED 2017

#define FLARE_EVENT_MESSAGE_UNMARKED 2018

#define FLARE_EVENT_MESSAGE_PRESENCE_CHANGED 2019

#define FLARE_EVENT_MESSAGE_CUSTOM 2020

#define FLARE_EVENT_CONVERSATION_SYNCED 3001

#define FLARE_EVENT_CONVERSATION_CREATED 3002

#define FLARE_EVENT_CONVERSATION_UPDATED 3003

#define FLARE_EVENT_CONVERSATION_UNREAD_COUNT_CHANGED 3004

#define FLARE_EVENT_CONVERSATION_DELETED 3005

#define FLARE_EVENT_NOTIFICATION_RECEIVED 3501

#define FLARE_EVENT_SYNC_STARTED 4001

#define FLARE_EVENT_SYNC_FINISHED 4002

#define FLARE_EVENT_SYNC_FAILED 4003

#define FLARE_EVENT_SYNC_PROGRESS 4004

#define FLARE_EVENT_SYNC_TASK_COMPLETED 4005

#define FLARE_EVENT_SYNC_STATE_CHANGED 4006

#define FLARE_EVENT_SYNC_RESYNC_NEEDED 4007

#define FLARE_EVENT_VIEW_UPDATED 6001

#define FLARE_EVENT_EXTENSION 5001

/**
 * 订阅句柄
 */
typedef uint64_t FlareSubscriptionHandle;

/**
 * 句柄类型
 */
typedef uint64_t FlareHandle;

/**
 * 输出字符串 (Rust 分配,调用方释放)
 */
typedef struct FlareString {
  char *ptr;
  size_t len;
} FlareString;

/**
 * 事件回调
 */
typedef void (*FlareEventCallback)(void *context, int32_t event_type, struct FlareString event_json);

/**
 * 批量事件回调
 */
typedef void (*FlareEventBatchCallback)(void *context,
                                        size_t event_count,
                                        struct FlareString events_json);

/**
 * 错误结构
 */
typedef struct FlareError {
  int32_t code;
  struct FlareString message;
  struct FlareString details_json;
} FlareError;

/**
 * 结果回调
 */
typedef void (*FlareResultCallback)(void *context,
                                    const struct FlareError *error,
                                    struct FlareString result_json);

/**
 * 输入字节视图 (调用方持有)
 */
typedef struct FlareBytesView {
  const uint8_t *ptr;
  size_t len;
} FlareBytesView;

/**
 * 输出字节 (Rust 分配,调用方释放)
 */
typedef struct FlareBytes {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} FlareBytes;

/**
 * 输入字符串视图 (调用方持有)
 */
typedef struct FlareStringView {
  const char *ptr;
  size_t len;
} FlareStringView;

/**
 * 进度回调
 */
typedef void (*FlareProgressCallback)(void *context, uint64_t current, uint64_t total);

/**
 * 任务句柄
 */
typedef uint64_t FlareTaskHandle;



FlareSubscriptionHandle flare_event_subscribe(FlareHandle handle,
                                              void *context,
                                              FlareEventCallback callback);

FlareSubscriptionHandle flare_event_subscribe_batch(FlareHandle handle,
                                                    void *context,
                                                    FlareEventBatchCallback callback);

void flare_event_unsubscribe(FlareSubscriptionHandle subscription);

void flare_event_unsubscribe_all(void);

/**
 * Universal contract invoke: `api_id` + JSON params (canonical ids from `contract/apis.json`).
 */
int32_t flare_sdk_invoke_json(FlareHandle handle,
                              const char *api_id,
                              const char *params_json,
                              void *context,
                              FlareResultCallback callback);

/**
 * C ABI: `flare_message_dispatch_json`
 */
int32_t flare_message_dispatch_json(FlareHandle handle,
                                    const char *op,
                                    const char *params_json,
                                    void *context,
                                    FlareResultCallback callback);

/**
 * C ABI: `flare_message_build_json`
 */
int32_t flare_message_build_json(FlareHandle handle,
                                 const char *request_json,
                                 void *context,
                                 FlareResultCallback callback);

/**
 * C ABI: `flare_media_dispatch_json`
 */
int32_t flare_media_dispatch_json(FlareHandle handle,
                                  const char *op,
                                  const char *params_json,
                                  void *context,
                                  FlareResultCallback callback);

/**
 * C ABI: `flare_capability_dispatch_json`
 */
int32_t flare_capability_dispatch_json(FlareHandle handle,
                                       const char *op,
                                       const char *params_json,
                                       void *context,
                                       FlareResultCallback callback);

int32_t flare_sdk_state(FlareHandle handle);

int32_t flare_sdk_disconnect(FlareHandle handle, void *context, FlareResultCallback callback);

int32_t flare_sdk_sync_conversation(FlareHandle handle,
                                    const char *conversation_id,
                                    void *context,
                                    FlareResultCallback callback);

int32_t flare_sdk_sync_messages(FlareHandle handle,
                                const char *conversation_id,
                                uint64_t last_seq,
                                int32_t limit,
                                void *context,
                                FlareResultCallback callback);

int32_t flare_sdk_get_user_presence(FlareHandle handle,
                                    const char *user_id,
                                    void *context,
                                    FlareResultCallback callback);

int32_t flare_sdk_batch_get_user_presence(FlareHandle handle,
                                          const char *user_ids_json,
                                          void *context,
                                          FlareResultCallback callback);

int32_t flare_sdk_subscribe_user_presence(FlareHandle handle,
                                          const char *user_ids_json,
                                          void *context,
                                          FlareResultCallback callback);

int32_t flare_message_create_text(FlareHandle handle,
                                  const char *conversation_id,
                                  const char *text,
                                  void *context,
                                  FlareResultCallback callback);

int32_t flare_message_send(FlareHandle handle,
                           const char *message_json,
                           void *context,
                           FlareResultCallback callback);

int32_t flare_message_list(FlareHandle handle,
                           const char *conversation_id,
                           uint64_t before_seq,
                           int32_t limit,
                           void *context,
                           FlareResultCallback callback);

int32_t flare_message_recall(FlareHandle handle,
                             const char *conversation_id,
                             const char *message_id,
                             void *context,
                             FlareResultCallback callback);

int32_t flare_message_delete(FlareHandle handle,
                             const char *conversation_id,
                             const char *message_id,
                             void *context,
                             FlareResultCallback callback);

int32_t flare_media_upload_file(FlareHandle handle,
                                const char *path,
                                const char *options_json,
                                void *context,
                                FlareResultCallback callback);

int32_t flare_media_upload_image(FlareHandle handle,
                                 const char *path,
                                 const char *options_json,
                                 void *context,
                                 FlareResultCallback callback);

int32_t flare_media_upload_video(FlareHandle handle,
                                 const char *path,
                                 const char *options_json,
                                 void *context,
                                 FlareResultCallback callback);

int32_t flare_media_upload_bytes(FlareHandle handle,
                                 struct FlareBytesView bytes,
                                 const char *file_name,
                                 const char *mime_type,
                                 const char *options_json,
                                 void *context,
                                 FlareResultCallback callback);

int32_t flare_media_delete_file(FlareHandle handle,
                                const char *file_id,
                                bool hard_delete,
                                void *context,
                                FlareResultCallback callback);

int32_t flare_media_cancel_user_file_download(FlareHandle handle,
                                              const char *download_key,
                                              void *context,
                                              FlareResultCallback callback);

int32_t flare_media_download_file_to_downloads(FlareHandle handle,
                                               const char *request_json,
                                               void *context,
                                               FlareResultCallback callback);

void flare_string_free(struct FlareString s);

void flare_bytes_free(struct FlareBytes b);

void flare_error_free(struct FlareError e);

/**
 * 释放由 `Box::into_raw` 传入 Dart 回调的 [`FlareError`]（须与 [`crate::executor`] 堆分配错误成对使用）。
 *
 * # Safety
 * `ptr` 须为 null，或由本 crate 经 `Box::into_raw` 分配且仅释放一次的合法指针。
 */
void flare_error_heap_free(struct FlareError *ptr);

FlareHandle flare_sdk_create(void);

void flare_sdk_release(FlareHandle handle);

/**
 * FFI 全局硬重置：取消全部事件订阅并释放全部 SDK 句柄。
 *
 * 用途：Flutter/iOS 热重启后，旧 isolate 的回调地址可能失效。
 * 在新 isolate 初始化前调用可避免旧后台任务继续回调导致崩溃。
 */
void flare_sdk_hard_reset(void);

int32_t flare_sdk_init(FlareHandle handle,
                       const char *config_json,
                       void *context,
                       FlareResultCallback callback);

int32_t flare_sdk_uninit(FlareHandle handle, void *context, FlareResultCallback callback);

int32_t flare_sdk_login(FlareHandle handle,
                        const char *user_id,
                        const char *token,
                        const char *store_config_json,
                        void *context,
                        FlareResultCallback callback);

/**
 * 预热登录会话：开 per-user 本地库 + 装配引擎，**不连网**。
 *
 * 与 [`flare_sdk_connect`] 配合实现「初始化前置、登录只做网络」：App 启动即可对
 * 「上次登录用户」调用本函数，把开库 / 迁移 / 建引擎移出登录关键路径。
 */
int32_t flare_sdk_prepare(FlareHandle handle,
                          const char *user_id,
                          const char *store_config_json,
                          void *context,
                          FlareResultCallback callback);

/**
 * 连接已 [`flare_sdk_prepare`] 预热好的会话并完成首次同步（登录的网络半段）。
 */
int32_t flare_sdk_connect(FlareHandle handle,
                          const char *user_id,
                          const char *token,
                          void *context,
                          FlareResultCallback callback);

int32_t flare_sdk_logout(FlareHandle handle, void *context, FlareResultCallback callback);

int32_t flare_sdk_update_access_token(FlareHandle handle,
                                      const char *access_token,
                                      const char *tenant_id,
                                      void *context,
                                      FlareResultCallback callback);

struct FlareString flare_sdk_version(void);

struct FlareString flare_sdk_ffi_contract_version(void);

int32_t flare_sdk_data_root(FlareHandle handle, void *context, FlareResultCallback callback);

bool flare_sdk_is_connected(FlareHandle handle);

bool flare_sdk_session_active(FlareHandle handle);

int32_t flare_sdk_current_user_id(FlareHandle handle, void *context, FlareResultCallback callback);

struct FlareString flare_sdk_generate_core_token(const char *secret,
                                                 const char *issuer,
                                                 const char *user_id,
                                                 const char *device_id,
                                                 const char *tenant_id,
                                                 uint64_t ttl_secs);

#endif  /* FLARE_IM_CORE_SDK_FFI_H */
