import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from './theme/tokens';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loginSafeArea: {
    backgroundColor: '#171a20',
  },
  keyboardAvoiding: {
    flex: 1,
  },
  content: {
    paddingVertical: spacing.page,
  },
  loginContent: {
    flexGrow: 1,
    paddingVertical: 0,
  },
  loginScreen: {
    backgroundColor: '#171a20',
    flexGrow: 1,
    minHeight: '100%',
  },
  loginHeroPanel: {
    alignItems: 'center',
    backgroundColor: '#7540f2',
    height: 252,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 24,
  },
  loginGridLayer: {
    bottom: 0,
    left: 0,
    opacity: 0.32,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  loginGridVertical: {
    backgroundColor: '#ffffff',
    bottom: 0,
    position: 'absolute',
    top: 0,
    width: StyleSheet.hairlineWidth,
  },
  loginGridHorizontal: {
    backgroundColor: '#ffffff',
    height: StyleSheet.hairlineWidth,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  loginBrandIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    height: 64,
    justifyContent: 'center',
    marginBottom: 12,
    width: 64,
  },
  loginBrandName: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '900',
  },
  loginBrandTagline: {
    color: '#f4f0ff',
    fontSize: 14,
    marginTop: 4,
  },
  loginPanel: {
    paddingHorizontal: 14,
    paddingTop: 30,
  },
  loginTitle: {
    color: '#f7f8fb',
    fontSize: 24,
    fontWeight: '900',
  },
  loginSubtitle: {
    color: '#a5abb6',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  loginFieldGroup: {
    marginTop: 26,
  },
  loginLabel: {
    color: '#f4f6fb',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 10,
  },
  loginInputRow: {
    alignItems: 'center',
    backgroundColor: '#20242c',
    borderColor: '#343945',
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  loginTextInput: {
    color: '#f7f8fb',
    flex: 1,
    fontSize: 16,
    minHeight: 46,
    padding: 0,
  },
  loginHintRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
  },
  loginHintText: {
    color: '#8f96a3',
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
  },
  loginSelectRow: {
    alignItems: 'center',
    backgroundColor: '#20242c',
    borderColor: '#343945',
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 58,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  loginSelectValue: {
    color: '#f7f8fb',
    fontSize: 16,
    fontWeight: '800',
  },
  loginSelectDetail: {
    color: '#8f96a3',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  loginDropdown: {
    backgroundColor: '#20242c',
    borderColor: '#343945',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    marginTop: 8,
    overflow: 'hidden',
  },
  loginDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  loginDropdownItemActive: {
    backgroundColor: '#2b2346',
  },
  loginDropdownLabel: {
    color: '#f7f8fb',
    fontSize: 15,
    fontWeight: '800',
  },
  loginDropdownLabelActive: {
    color: '#a98dff',
  },
  loginDropdownDetail: {
    color: '#8f96a3',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  loginDisclosure: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    minHeight: 40,
  },
  loginDisclosureText: {
    color: '#c8ccd5',
    fontSize: 15,
    fontWeight: '700',
  },
  loginServerPanel: {
    backgroundColor: '#20242c',
    borderColor: '#343945',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  loginConfigRow: {
    alignItems: 'center',
    borderBottomColor: '#303541',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  loginConfigLabel: {
    color: '#f4f6fb',
    fontSize: 15,
    fontWeight: '700',
    width: 74,
  },
  loginConfigInput: {
    color: '#f7f8fb',
    flex: 1,
    fontSize: 14,
    minHeight: 46,
    padding: 0,
  },
  loginButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    height: 48,
    justifyContent: 'center',
    marginTop: 28,
  },
  loginButtonDisabled: {
    opacity: 0.55,
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  loginFootnote: {
    color: '#8f96a3',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
    textAlign: 'center',
  },
  loginStatusBar: {
    alignItems: 'center',
    borderColor: '#313742',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 14,
    marginTop: 96,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  loginStatusPill: {
    borderColor: '#313742',
    borderRadius: 7,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  loginStatusPillReady: {
    backgroundColor: '#0d3324',
    borderColor: '#175c3d',
  },
  loginStatusPillText: {
    color: '#25d87f',
    fontSize: 12,
    fontWeight: '800',
  },
  loginStatusText: {
    color: '#9ba2ad',
    flex: 1,
    fontSize: 12,
  },
  header: {
    paddingHorizontal: spacing.page,
    paddingBottom: spacing.section,
  },
  authHero: {
    paddingBottom: spacing.section,
  },
  authSubtitle: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  kicker: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  title: {
    color: colors.text,
    fontSize: 32,
    fontWeight: '900',
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    position: 'absolute',
    right: spacing.page,
    top: spacing.page,
  },
  headerBadgeAnchor: {
    height: 20,
    width: 20,
  },
  modeTabs: {
    flexDirection: 'row',
    gap: 8,
    marginTop: spacing.section,
  },
  segmentButton: {
    alignItems: 'center',
    backgroundColor: '#eef0f5',
    borderRadius: 8,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  segmentButtonActive: {
    backgroundColor: colors.primary,
  },
  segmentText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: '#fff',
  },
  iconAction: {
    alignItems: 'center',
    backgroundColor: '#eef0f5',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  iconActionPrimary: {
    backgroundColor: colors.primary,
  },
  iconActionActive: {
    backgroundColor: colors.primaryDark,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    padding: spacing.section,
  },
  summaryCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    padding: spacing.section,
  },
  summaryTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  summaryMeta: {
    color: colors.textMuted,
    fontSize: 13,
    marginTop: 4,
  },
  syncPanel: {
    alignItems: 'stretch',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    padding: spacing.page,
  },
  syncIcon: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#f1edff',
    borderRadius: 30,
    height: 60,
    justifyContent: 'center',
    marginBottom: spacing.section,
    width: 60,
  },
  syncIconDone: {
    backgroundColor: '#e8f8f0',
  },
  syncIconFailed: {
    backgroundColor: '#fff0f0',
  },
  syncTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  syncDetail: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: spacing.section,
    marginTop: 4,
  },
  syncStats: {
    backgroundColor: colors.background,
    borderRadius: radius.card,
    paddingHorizontal: spacing.section,
  },
  cardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.item,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  sectionLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '900',
  },
  filterRow: {
    gap: 8,
    paddingRight: spacing.page,
  },
  inputListBody: {
    borderBottomWidth: 0,
    borderTopWidth: 0,
  },
  runtimeBanner: {
    alignItems: 'center',
    borderRadius: radius.card,
    flexDirection: 'row',
    gap: 8,
    padding: spacing.section,
  },
  runtimeBannerSuccess: {
    backgroundColor: '#e8f8f0',
  },
  runtimeBannerWarning: {
    backgroundColor: '#fff7e6',
  },
  runtimeBannerError: {
    backgroundColor: '#fff0f0',
  },
  runtimeDot: {
    borderRadius: 6,
    height: 12,
    width: 12,
  },
  runtimeText: {
    color: colors.text,
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  conversationRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.section,
    paddingVertical: 12,
  },
  conversationRowActive: {
    backgroundColor: colors.cardMuted,
    borderRadius: radius.card,
    paddingHorizontal: 8,
  },
  rowDivider: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  avatar: {
    alignItems: 'center',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  avatarText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  presenceDot: {
    borderColor: colors.card,
    borderRadius: 6,
    borderWidth: 2,
    bottom: 0,
    height: 12,
    position: 'absolute',
    right: 0,
    width: 12,
  },
  conversationBody: {
    flex: 1,
    gap: 4,
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  titleInline: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  conversationTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  previewText: {
    color: colors.textMuted,
    flex: 1,
    fontSize: 14,
    marginRight: spacing.item,
  },
  metaText: {
    color: colors.textMuted,
    fontSize: 12,
  },
  unreadBadge: {
    backgroundColor: colors.primary,
  },
  emptyInline: {
    color: colors.textMuted,
    fontSize: 14,
    paddingVertical: 16,
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    padding: 32,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyDetail: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  chatAppBar: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    padding: 8,
  },
  avatarSmall: {
    alignItems: 'center',
    borderRadius: 19,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  avatarSmallText: {
    color: '#fff',
    fontWeight: '900',
  },
  chatIdentity: {
    flex: 1,
  },
  chatTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  presenceText: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  pinnedBar: {
    alignItems: 'center',
    backgroundColor: colors.cardMuted,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    padding: spacing.section,
  },
  pinnedText: {
    color: colors.text,
    flex: 1,
    fontWeight: '700',
  },
  timelineCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  timeline: {
    gap: spacing.section,
    padding: spacing.section,
  },
  timeDivider: {
    alignSelf: 'center',
    backgroundColor: '#eef0f5',
    borderRadius: radius.pill,
    color: colors.textMuted,
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  messageRow: {
    flexDirection: 'row',
    maxWidth: '90%',
  },
  messageRowInbound: {
    alignSelf: 'flex-start',
  },
  messageRowOutbound: {
    alignSelf: 'flex-end',
  },
  selectionDot: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    marginRight: 6,
    marginTop: 28,
    width: 20,
  },
  selectionDotActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  senderAvatar: {
    alignItems: 'center',
    backgroundColor: '#dfefff',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    marginRight: 8,
    marginTop: 18,
    width: 32,
  },
  senderAvatarText: {
    color: colors.avatarPeer,
    fontWeight: '900',
  },
  messageStack: {
    maxWidth: 260,
  },
  authorLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 4,
  },
  authorLabelOutbound: {
    alignSelf: 'flex-end',
  },
  bubble: {
    borderRadius: radius.bubble,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mediaBubble: {
    alignItems: 'center',
    minHeight: 56,
    minWidth: 56,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  inboundBubble: {
    backgroundColor: colors.inbound,
    borderColor: colors.border,
    borderWidth: StyleSheet.hairlineWidth,
  },
  outboundBubble: {
    backgroundColor: colors.outbound,
  },
  failedBubble: {
    borderColor: colors.danger,
    borderWidth: 1,
  },
  bubbleText: {
    fontSize: 16,
    lineHeight: 22,
  },
  mediaText: {
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
    textAlign: 'center',
  },
  inboundText: {
    color: colors.text,
  },
  outboundText: {
    color: '#fff',
  },
  messageActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  messageActionRowOutbound: {
    alignSelf: 'flex-end',
  },
  messageMeta: {
    color: colors.textMuted,
    fontSize: 11,
  },
  retryText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '800',
  },
  reactionStrip: {
    alignSelf: 'flex-start',
    backgroundColor: colors.cardMuted,
    borderRadius: radius.pill,
    flexDirection: 'row',
    gap: 3,
    marginTop: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  reactionStripOutbound: {
    alignSelf: 'flex-end',
  },
  reactionText: {
    fontSize: 13,
  },
  quickMessageActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  quickMessageActionsOutbound: {
    alignSelf: 'flex-end',
  },
  quickActionText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  batchToolbar: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: spacing.section,
  },
  batchTitle: {
    color: colors.text,
    fontWeight: '900',
  },
  uploadTask: {
    marginTop: spacing.item,
  },
  uploadName: {
    color: colors.text,
    fontWeight: '800',
  },
  progressRail: {
    backgroundColor: '#eef0f5',
    borderRadius: radius.pill,
    height: 6,
    marginTop: 6,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.primary,
    height: 6,
  },
  composerCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    padding: spacing.section,
  },
  replyPreview: {
    alignItems: 'center',
    backgroundColor: colors.cardMuted,
    borderRadius: radius.card,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.item,
    padding: spacing.item,
  },
  replyTitle: {
    color: colors.primary,
    fontWeight: '900',
  },
  replyText: {
    color: colors.textMuted,
    maxWidth: 240,
  },
  composerTools: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: spacing.item,
  },
  panelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: spacing.item,
  },
  emojiTile: {
    alignItems: 'center',
    backgroundColor: colors.cardMuted,
    borderRadius: radius.card,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  emojiText: {
    fontSize: 24,
  },
  stickerTile: {
    alignItems: 'center',
    backgroundColor: '#e8f8f0',
    borderRadius: radius.card,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  stickerText: {
    color: colors.success,
    fontWeight: '800',
  },
  formatBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: spacing.item,
  },
  attachmentGrid: {
    flexDirection: 'column',
    gap: 10,
    marginBottom: spacing.item,
  },
  attachmentGroup: {
    gap: 8,
  },
  attachmentGroupTitle: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  attachmentGroupItems: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  attachmentItem: {
    alignItems: 'center',
    backgroundColor: colors.cardMuted,
    borderRadius: radius.card,
    minWidth: 78,
    padding: 10,
  },
  attachmentText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  detailActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: spacing.item,
  },
  accountHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.item,
  },
  accountAvatar: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  accountAvatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  moreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  moreAction: {
    alignItems: 'center',
    backgroundColor: '#f6f7fb',
    borderRadius: radius.card,
    flexDirection: 'row',
    gap: 6,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  moreActionText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  dangerText: {
    color: colors.danger,
  },
  statusLine: {
    fontSize: 13,
    lineHeight: 19,
    marginBottom: spacing.section,
  },
  keyValueRow: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 9,
  },
  keyText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  valueText: {
    color: colors.text,
    flex: 1,
    fontSize: 12,
    marginLeft: 14,
    textAlign: 'right',
  },
  capabilityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: spacing.item,
  },
  capabilityPill: {
    backgroundColor: colors.cardMuted,
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  capabilityText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '700',
  },
  labButtonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  labButtonCell: {
    marginBottom: 8,
    paddingHorizontal: 4,
    width: '50%',
  },
  labResultText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  eventRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 8,
  },
  eventIndex: {
    backgroundColor: colors.cardMuted,
    borderRadius: radius.pill,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    minWidth: 24,
    paddingVertical: 3,
    textAlign: 'center',
  },
  eventText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
});
