package com.flare.im.model.event

/** GENERATED. Do not edit by hand. */
/** Common event envelope emitted by every platform SDK event stream. */
data class SdkEventEnvelope(
    /** wire: `eventId`. Unique event id generated by the SDK adapter. */
    val eventId: String = "",
    /** wire: `kind`. Top-level event domain. */
    val kind: SdkEventKind,
    /** wire: `name`. Domain-specific event name. */
    val name: String = "",
    /** wire: `occurredAt`. Event time in milliseconds. */
    val occurredAt: Long = 0L,
    /** wire: `traceId`. Trace id for diagnostics when available. */
    val traceId: String? = null,
    /** wire: `payload`. Raw event payload for forward-compatible consumers. */
    val payload: Map<String, Any?> = emptyMap(),
)
