// GENERATED. Do not edit by hand.
import 'sdk_event_kind.dart';

/// Common event envelope emitted by every platform SDK event stream.
final class SdkEventEnvelope {
  /// wire: `eventId`. Unique event id generated by the SDK adapter.
  final String eventId;
  /// wire: `kind`. Top-level event domain.
  final SdkEventKind kind;
  /// wire: `name`. Domain-specific event name.
  final String name;
  /// wire: `occurredAt`. Event time in milliseconds.
  final int occurredAt;
  /// wire: `traceId`. Trace id for diagnostics when available.
  final String? traceId;
  /// wire: `payload`. Raw event payload for forward-compatible consumers.
  final Map<String, Object?> payload;

  const SdkEventEnvelope({
    this.eventId = '',
    required this.kind,
    this.name = '',
    this.occurredAt = 0,
    this.traceId,
    this.payload = const {},
  });
}
