import Foundation

/// GENERATED. Do not edit by hand.
/// Common event envelope emitted by every platform SDK event stream.
public struct SdkEventEnvelope: Sendable {
    /// wire: `eventId`. Unique event id generated by the SDK adapter.
    public let eventId: String
    /// wire: `kind`. Top-level event domain.
    public let kind: SdkEventKind
    /// wire: `name`. Domain-specific event name.
    public let name: String
    /// wire: `occurredAt`. Event time in milliseconds.
    public let occurredAt: UInt64
    /// wire: `traceId`. Trace id for diagnostics when available.
    public let traceId: String?
    /// wire: `payload`. Raw event payload for forward-compatible consumers.
    public let payload: [String: AnySendable]

    public init(eventId: String = "", kind: SdkEventKind, name: String = "", occurredAt: UInt64 = 0, traceId: String? = nil, payload: [String: AnySendable] = [:]) {
        self.eventId = eventId
        self.kind = kind
        self.name = name
        self.occurredAt = occurredAt
        self.traceId = traceId
        self.payload = payload
    }
}
