export const flutterAlignedWorkbenchCapabilities = [
  "auth.login",
  "auth.logout",
  "auth.updateAccessToken",
  "conversation.bootstrapHomeTimeline",
  "conversation.openTimeline",
  "conversation.openSingleChat",
  "conversation.openGroupChat",
  "conversation.pin",
  "conversation.mute",
  "conversation.archive",
  "conversation.markRead",
  "conversation.markUnread",
  "conversation.clearLocalHistory",
  "conversation.draft",
  "message.buildTypedMessage",
  "message.sendMessage",
  "message.sendMessageNoOss",
  "message.searchMessages",
  "message.editText",
  "message.editRichDoc",
  "message.deleteForSelf",
  "message.deleteForEveryone",
  "message.reactions",
  "message.pin",
  "message.reply",
  "message.typing",
  "message.readAndBurn",
  "media.uploadFile",
  "media.uploadImage",
  "media.uploadVideo",
  "media.uploadBytes",
  "media.downloadFile",
  "media.cacheRemote",
  "media.resolveAccess",
  "media.cacheStats",
  "capability.dispatch",
  "capability.grant",
  "capability.revoke",
  "connection.getState",
  "connection.notifyNetworkChange",
  "connection.disconnect",
  "session.currentUser",
  "session.runtimeHealth",
  "session.updateAccessToken",
  "session.heartbeat",
  "events.subscribeEvents",
  "presence.getPresence",
  "presence.subscribeUserPresence",
] as const;

export type FlutterAlignedWorkbenchCapability = (typeof flutterAlignedWorkbenchCapabilities)[number];

export const flutterAlignedWorkbenchScreens = [
  "login",
  "sync",
  "conversations",
  "chat",
  "message-search",
  "sdk-lab",
] as const;

export type FlutterAlignedWorkbenchScreen = (typeof flutterAlignedWorkbenchScreens)[number];
