package com.flare.im.model.catalog

/** GENERATED. Do not edit by hand. */
/** Dispatch op passed to flare_message_build_json. */
enum class MessageBuildOp { CREATE_TEXT, CREATE_QUOTE, CREATE_THREAD_REPLY, CREATE_FORWARD, CREATE_IMAGE, CREATE_IMAGE_GROUP, CREATE_VIDEO, CREATE_AUDIO, CREATE_FILE, CREATE_EMOJI, CREATE_LOCATION, CREATE_STICKER, CREATE_LINK_CARD, CREATE_CARD, CREATE_MINI_PROGRAM, CREATE_RICH_DOC, CREATE_SYSTEM, CREATE_NOTIFICATION, CREATE_VOTE, CREATE_TASK, CREATE_SCHEDULE, CREATE_ANNOUNCEMENT, CREATE_CUSTOM, CREATE_PLACEHOLDER, CREATE_WITH_CONTENT }
